### PR TITLE
Create extra emojis and fix tired, frowning with open mouth faces

### PR DESCRIPTION
**Pull request by carlinmack**

### CODE REVIEW

**Comment by carlinmack** [comment]
build is failing because it can't see the file?

**Comment by b-g** [comment]
Hi @carlinmack Great! Just tests are red ... I believe it is simply because the file names are wrong.

Should be E280.svg E281.svg. Currently E280.svg 1E281.svg. Note the not correct `1` at the beginning of the file name.

**Comment by carlinmack** [comment]
good catch, no idea how that happened

**Comment by b-g** [comment]
@carlinmack Thanks for the quick fix! Merged!

**Comment by carlinmack** [comment]
#72

**Pull request merged**
