### PR TITLE
Redesign sari

### PR DESCRIPTION
**Pull request by carlinmack**
Proud of this, just want to make sure you approve before merging :)

### CODE REVIEW

**Comment by b-g** [comment]
Hi @carlinmack Super great that you tackle it! And yes it works now really well in terms of bringing across that a Sari is a very long piece of cloth (wrapped around the body)! Great! 

Just could you make the Sari a bit more geometrical? Your new sari is very different in terms of curve details in comparison to the other OpenMoji "clothing" https://openmoji.org/library/#search=clothing :)

**Comment by b-g** [comment]
@carlinmack 
Twitter did a redesign as well after some feedback on social media e.g. https://twitter.com/bhaggs/status/1194718642581098496 ... Also I'm not sure whether it should look like a belly top.

cc
Hi @gurmukhp, could you advice us on the Sari emoji?

**Comment by carlinmack** [comment]
what do you mean belly top? 

Some of my friends are familiar and "sari" refers to one piece of cloth that's wrapped around the body, the purple part in the emoji I created. It's more common to wear it with a top which is the red part in the emoji.

**Comment by b-g** [comment]
Great + answered with: "it's more common to expose the area above the belly button". Just wanted to double check this as other vendor emojis differ in exposing / not exposing the belly.

**Comment by carlinmack** [comment]
Thoughts on improved version?

**Comment by b-g** [comment]
@carlinmack Thanks! Look like a nice compromise in a good way. Still very organic but probably very hard to find a real minimal geometric version. I tweaked the stroke weights to 1.5 px (to make it look more like the rest) and then simplified a bit the lines. Hope that is fine for you. If not ... feel free to tweak it further via direct commits to master / happy to give more feedback etc.

Merged

**Comment by carlinmack** [comment]
looks good! I didn't realise the stroke was thinner, thanks for fixing and merging :)

**Pull request merged**
