### PR TITLE
Adding Alabama flag

### PR DESCRIPTION
**Pull request by Kirylchyk**
@b-g opening PR to add Alabama flag 

**local test results** -> i assume same issue as previous time

`varia@varia:~/Desktop/my_code_projects/openmoji$ npm run test-dev

> openmoji@15.0.0 test-dev
> mocha --parallel --reporter min --invert --grep "production" test/*.{js,mjs} --openmoji-data-json $PWD/data/openmoji.json --openmoji-src-folder $PWD/src

  55627 passing (1m)
  1 failing

  1) Data integrity openmoji.json
       Hexcode and emoji property matches in openmoji.json?
         🏴 1F3F4-E0061-E0076-E007F property should be matching:

      AssertionError: expected '1F3F4-E0061-E0076-E007F' to equal '1F3F4'
      + expected - actual

      -1F3F4-E0061-E0076-E007F
      +1F3F4
      
      at Context.<anonymous> (test/data.js:30:44)
      at process.processImmediate (node:internal/timers:476:21)

`

### CODE REVIEW

**Comment by Kirylchyk** [comment]
Thank you

**Comment by Kirylchyk** [comment]
For reference https://en.wikipedia.org/wiki/Flag_of_Alabama

**Comment by b-g** [comment]
@Kirylchyk Many thanks for this! Please run `npm run generate-data-tables` and then `npm run test-dev`. The problem was, that the line you've added to `data/extras-unicode.csv` introduced additional columns. I fixed it, but would be nice not have to do it for every upcoming US subdivision flag :)

**Comment by b-g** [comment]
After the merged ... I saw that the flag is slightly buggy ... please fix:

Screen Shot 2024-04-12 at 09 51 12

**Comment by Kirylchyk** [comment]
> @Kirylchyk Many thanks for this! Please run `npm run generate-data-tables` and then `npm run test-dev`. The problem was, that the line you've added to `data/extras-unicode.csv` introduced additional columns. I fixed it, but would be nice not have to do it for every upcoming US subdivision flag :)
> 
> Screen Shot 2024-04-12 at 09 45 19

Thank you! Will double check next time

**Comment by Kirylchyk** [comment]
> After the merged ... I saw that the flag is slightly buggy ... please fix:
> 
> Screen Shot 2024-04-12 at 09 51 12

Indeed, my bad, will create the PR with updates asap

**Pull request merged**
