### PR TITLE
Improve consistency of prohibited signs #164

### PR DESCRIPTION
**Pull request by carlinmack**

### CODE REVIEW

**Comment by carlinmack** [comment]
image
I hope people don't still make SVGs like this!

**Comment by carlinmack** [comment]
I tried to make the 18 consistent with our font, but very difficult
image

**Comment by carlinmack** [comment]
image
proceeding with the right one as it is clearer, though it is flipped from our handshake emoji

**Comment by carlinmack** [comment]
image
thoughts?

**Comment by carlinmack** [comment]
will export files and fix build if you think that extras-openmoji/symbols is a good place and E380 is a good name for No Handshake

**Comment by b-g** [comment]
Great!! But see https://github.com/hfg-gmuend/openmoji/issues/164#issuecomment-609606958. Sorry! Yes extras-openmoji/symbols or extras-openmoji/healthcare?

**Comment by carlinmack** [comment]
sorry I meant this as a halfway commit

**Comment by carlinmack** [comment]
image
thoughts? looks unaligned even though it is 
image

**Pull request merged**
