### PR TITLE
Add narwhal, beluga, porpoise, and replace dolphin

### PR DESCRIPTION
**Pull request by kriskowal**
This change adds a consistent set of cetaceans, building on the existing orca
and blue whale (spouting and otherwise).

This replaces the existing dolphin.
The others are new extras.

Per cetacean proposal #161

### CODE REVIEW

**Comment by b-g** [comment]
Dolphin: 

- I think the grey of the "belly" should be under the fin, see the emojis of other vendors
2020-04-06 at 12 01
- also it might look better if the top fin is slightly more downwards (very rough sketch not a suggestion for the final curve) e.g.
2020-04-06 at 12 01

**Comment by b-g** [comment]
- Find the angle of the horn slightly of the general direction / momentum of the body
- Would not add a grey fill on top of the horn
2020-04-06 at 12 11

**Comment by b-g** [comment]
Very nice! Tiny detail: the line endings / curve join points of the light grey fin could be probably improved. The position where the fin joins the body looks too small IMO.

2020-04-06 at 12 14

**Comment by b-g** [comment]
Same issue like described above at the dolphin. 

2020-04-06 at 12 18

**Comment by b-g** [comment]
@kriskowal But really nice set! 🙏

**Comment by kriskowal** [comment]
Draft, before recutting.

extra-cetaceans-plate

Also, I've just cut out new codes in the private use area. I'm open to combining, say, whale + party horn = narwhal, whale + melon = beluga, dolphin + hippopotamus = porpoise. I'm sure whatever reasoning for combining will be inscrutable, but, your option.

**Comment by carlinmack** [comment]
We normally just cut out space in the private use area and name them E400, E401, E402 etc, but I like your style haha

**Comment by kriskowal** [comment]
I'll leave them in the private use area. Seems wisest in any case. I'll wait for another round of feedback from @b-g before updating the change.

**Comment by kriskowal** [comment]
Ah, and please weigh in on the color of dolphins. The other emoji sets are split between grey and blue, but more are blue. The narwhal and beluga should definitely be grey. I like the idea of distinguishing dolphin and porpoise in ways more obvious than the nose and fin, which is why I elected to flip along the vertical axis. Differentiating by color would I think be good for contrast. As always, I defer to your opinion!

**Comment by b-g** [comment]
@kriskowal Wow! That's all great (Row 2)! Happy to merge!

>  color of dolphins?

This is a hard one :) I would rather go with grey, simply as our other emojis in animal-marine have rather realistic colors and not so much the "comic-esk" blue. But please decide on your own, also if you think it helps to differentiate between porpoise blue is fine too. 

> Also, I've just cut out new codes in the private use area. I'm open to combining, say, whale + party horn = narwhal, whale + melon = beluga, dolphin + hippopotamus = porpoise. I'm sure whatever reasoning for combining will be inscrutable, but, your option.

Nice idea! But I would rather go with a single private area usecode to not increase the complexity further. Ideally a future Unicode Emoji Version has all those animals ... and then we can move them to standard Unicode hex code.

**Comment by b-g** [comment]
@kriskowal will wait for you final dolphin color decision and then merge. Let me know.

**Comment by kriskowal** [comment]
This is once again in a reviewable state.

I don’t know whether everyone already found this, but for my own verification, I found the button that lets you look at the images in the diff.

Screen Shot 2020-04-08 at 4 42 46 PM

**Comment by b-g** [comment]
@kriskowal Super! + Merged!

**Pull request merged**
