### PR TITLE
proposal for a UFP flag

### PR DESCRIPTION
**Pull request by fuddl**
the flag of [the fictional ufp](https://en.wikipedia.org/wiki/United_Federation_of_Planets). I think it is based on the UN flag. I decided to omit the text for the sake of simplicity.
ufp-google
1F1FA-1F1EB-1F1F5

### CODE REVIEW

**Comment by carlinmack** [comment]
Could you add the text like in the [Mayotte Flag](https://github.com/hfg-gmuend/openmoji/blob/master/color/618x618/1F1FE-1F1F9.png)? Thanks

**Comment by fuddl** [comment]
@carlinmack apart from the mapping. do you think the upper left is fitting?

**Comment by carlinmack** [comment]
Could you please post the figma link every time you mention it? I don't keep it open sorry :(

**Comment by carlinmack** [comment]
I've removed the notch for simplicity, feel free to export and make a PR :)

**Comment by fuddl** [comment]
regarding #203   
we could map this on something like `🏳️🟦🌌🌿`

🤷‍♂️

**Comment by carlinmack** [comment]
I think just `🏳️🟦🌌` is good. Alternatively what are your thoughts on:

`🇺🇳🪐` or `🇺🇳🌌`

**Comment by fuddl** [comment]
I like your fist proposal

**Comment by carlinmack** [comment]
out of interest why did you add the 🌿?

**Comment by fuddl** [comment]
Because of the wreath

**Comment by fuddl** [comment]
@carlinmack done

**Comment by fuddl** [comment]
no wait

**Comment by fuddl** [comment]
Done

**Comment by carlinmack** [comment]
I've tested this locally and everything is fine but I can't merge or run the tests again here 😐

**Comment by carlinmack** [comment]
gonna try cherry pick everything onto master and force-push. It'll definitely work but unfortunate that it has to be done

**Pull request merged**
