### PR TITLE
Add subdivision flag es-ct, Catalonia

### PR DESCRIPTION
**Pull request by jmontane**
I followed #248 (flag de-by, Bavaria). I hope everything is right with this PR.

### CODE REVIEW

**Comment by jmontane** [comment]
Hi,

I'm sorry, but I'm not a programmer guy. So, can you help me, please? What's wrong with this PR?

Thanks in advance

**Comment by b-g** [comment]
Hi @jmontane! Many thanks for the new flag! My apologies for the super slow response! But we needed a break :) Just debugged your contribution ... it took me quite a while, as the filename/hexcode of you contribution mixed 0 (null) and O (letter) which was very hard to spot 😂. Maybe next time take extra care on this nitty gritty detail :)

**Comment by jmontane** [comment]
Many thanks for your help, @b-g!

I'm sorry with 0 vs. O typo 😥

**Comment by b-g** [comment]
No worries! :) Many thanks for the flag!

**Pull request merged**
