### PR TITLE
Create extra pomegranate emoji

### PR DESCRIPTION
**Pull request by carlinmack**

### CODE REVIEW

**Comment by carlinmack** [comment]
I don't think this is good enough for two reasons:

1. probably too detailed
1. the non-colour version won't have any seeds. 

I tried a version with color+black line seeds but it looks quite strange with the 2px thickness.

**Comment by b-g** [comment]
For my eye it doesn't look bad! :)

Yes the marked area with the lines coming together is not optimal
2019-12-19 at 12 09

> the non-colour version won't have any seeds.

Can be fixed easily with defining an additional layer `line-supplement` and then simply drawing the seeds in black see the example https://openmoji.org/styleguide/#special_layers

cc @dnlutz

**Comment by carlinmack** [comment]
not important but the file accidentally sneaked in with PR #100, lets still improve it though :)

**Comment by b-g** [comment]
@carlinmack Conflicts here as well. Would then vote to merge it after resolving the conflicts straight away ... and then improve it with commits direct to master (at least add the seeds in black in line-supplement).

**Comment by carlinmack** [comment]
I think that should work lol, seeing as the file is already in the repo

**Comment by carlinmack** [comment]
apparently not, I'll have time tomorrow to fix it

**Comment by carlinmack** [comment]
@b-g merging as no conflicts now, I changed the lines like you showed in your picture

**Pull request merged**
