### PR TITLE
kirylchyk_added_flag_emoji_washingtonDC

### PR DESCRIPTION
**Pull request by Kirylchyk**
As per opened enhancement ticket https://github.com/hfg-gmuend/openmoji/issues/467, adding a new emoji for Washington DC flag

### CODE REVIEW

**Comment by b-g** [comment]
Many thanks for this! But please change the aspect ration following the other flags. Also make sure that running `npm run test-dev` produces no errors, currently this is not the case.

**Comment by Kirylchyk** [comment]
Modified aspect ration and ran `npm run test-dev`. Got 55585 passing, 1 failed due to hexcode, but i think it's not an issue as I am adding non-standard emoji. 

Thank you

**Comment by b-g** [comment]
Many thanks for the improvements! Close :) The stars seem to be distorted e.g. could you please fix them e.g. compare with https://en.wikipedia.org/wiki/Flag_of_Washington,_D.C. and the images below? Other than that, I think we are ready to merge.

2024-02-22 at 12 22

Screen Shot 2024-02-22 at 12 23 10

PS: I've fixed the hexcode issue, `npm run test-dev` is green now.

**Comment by Kirylchyk** [comment]
Thank you for your feedback. Sending the latest version for the approval.

**Comment by b-g** [comment]
Many thanks! Merged.

**Comment by Kirylchyk** [comment]
Thank you for your cooperation!

**Pull request merged**
