### PR TITLE
adding monochrome flags and browncoat flag

### PR DESCRIPTION
**Pull request by fuddl**
as proposed in #211 

Monochrome flags and browncoat flag and nail+gear

### CODE REVIEW

**Comment by b-g** [comment]
@fuddl Many thanks for this! But the tests are red:

```
   4 failing
 
   1) Data integrity openmoji.json
        Every hexcode is unique in openmoji.json?
          1F3F3-FE0F-200D-1F7E6 should be unique:
 
       AssertionError: expected 2 to equal 1
       + expected - actual
 
       -2
       +1
       
       at Context.<anonymous> (test/data.js:21:38)
 
   2) Data integrity openmoji.json
        Every hexcode is unique in openmoji.json?
          1F3F3-FE0F-200D-1F7E6 should be unique:
 
       AssertionError: expected 2 to equal 1
       + expected - actual
 
       -2
       +1
       
       at Context.<anonymous> (test/data.js:21:38)
 
   3) Data integrity openmoji.json
        Hexcode and emoji property matches in openmoji.json?
          ðŸ³ï¸â€ðŸŸ« 1F3F3-FE0F-200D-1F7E6 property should be matching:
 
       AssertionError: expected '1F3F3-1F7E6' to equal '1F3F3-1F7EB'
       + expected - actual
 
       -1F3F3-1F7E6
       +1F3F3-1F7EB
       
       at Context.<anonymous> (test/data.js:30:44)
 
   4) File integrity src files
        Source SVG files listed in openmoji.json?
          1F3F3-FE0F-200D-1F7EB.svg should be listed in openmoji.json:
      AssertionError: expected undefined to exist
       at Context.<anonymous> (test/file-exists-src.js:33:30)
 
```

Please fix :)

You can also run them locally with `npm test`

**Comment by fuddl** [comment]
@b-g can i suppress messages like:

```
  1) File integrity black/color production files
       Production svg files exist?
         🏳️ should have black/svg/1F3F3-FE0F.svg:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/file-exists-production.js:20:48)
```

?

**Comment by b-g** [comment]
Yes. Sorry! Should have explained it better. Use: `npm run test-dev`

- `npm test` all test including checking the production files
- `npm run test-dev` all test excluding checking the production files

**Comment by fuddl** [comment]
>     * `npm run test-dev` all test excluding checking the production files

mindblowing! Used the chance and added more shades one more nerdy flag. voilà:

```
➜  openmoji git:(generic-flags) ✗ npm run test-dev                                            

> openmoji@12.2.0 test-dev /Users/alex/Sites/openmoji
> mocha --reporter min --invert --grep "production" test/*.js --openmoji-data-json $PWD/data/openmoji.json --openmoji-src-folder $PWD/src



  45144 passing (1m)
```

🥳

**Comment by carlinmack** [comment]
The hello internet flag? very very cool!!!

**Comment by HaasJona** [comment]
Not sure if it matters, but why is the brown flag annotated as blue flag (twice)?

```
    "emoji": "🏳️‍🟫",
    "hexcode": "1F3F3-FE0F-200D-1F7EB",
    "group": "extras-unicode",
    "subgroups": "flag",
    "annotation": "blue flag",
```

**Comment by fuddl** [comment]
That's an error

**Comment by b-g** [comment]
@fuddl 

Please fix the annotation and we are ready to go! Happy to merge this ...

> mindblowing!

Yes ... glad that you like it :)

**Comment by fuddl** [comment]
@b-g 
> Please fix the annotation and we are ready to go! Happy to merge this ...

done

**Comment by b-g** [comment]
Many thanks! Merged!

**Comment by b-g** [comment]
@fuddl Quick question: I just released that you have choosen **extras-unicode** for all your flags. Hence is every Unicode Hexcode you've used in extras-unicode 100% official? Please confirm ... we otherwise have to move them to **extras-openmoji/flags**.

**Comment by b-g** [comment]
Hi @fuddl I undid the merge. Sorry! But I had a lot of errors generating the production files. Will have to investigate this. Stay tuned. cc @carlinmack

**Comment by b-g** [comment]
Could you do a new PR so that it appears again in the repo? Sorry for the back an forth ... but basically your PR broke our new build system and I have to figure out now why. Sorry to get entangled into this.

**Pull request merged**
