### PR TITLE
added iNaturalist logo

### PR DESCRIPTION
**Pull request by fuddl**
In #266 i forgot one important opendata project [iNaturalist](https://www.inaturalist.org/):

inaturalist openmoji

### CODE REVIEW

**Comment by b-g** [comment]
@fuddl Many thanks for this! Looks nice! Just I think you didn't update from Master (e.g. your PR would revert the  latest changes in `openmoji-emoji-unicode-missing.csv `) ... could you do that and update the PR accordingly? Cheers!

**Comment by fuddl** [comment]
@b-g sorry, I don't get it. The last commits on either repository are identical:

```
https://github.com/hfg-gmuend/openmoji/commit/7a968d008d786cb58ac0101d3c7412add781fb8b
     https://github.com/fuddl/openmoji/commit/7a968d008d786cb58ac0101d3c7412add781fb8b
```

see [master commits](https://github.com/hfg-gmuend/openmoji/commits/master) and [naturalist commits](https://github.com/fuddl/openmoji/commits/inaturalist)

**Comment by b-g** [comment]
@fuddl no is not :) See the diff of `openmoji-emoji-unicode-missing.csv`. I think you might ran `npm run generate-data-tables` without having done a `npm install` in a while. I've update a dependency :). Fixed and merged it. Happy start into the week. Best, B

**Comment by fuddl** [comment]
Ah, that's it. I'm sorry. Thanks for fixing

**Pull request merged**
