### PR TITLE
Consistency Issue #2 - moving eyes to the right

### PR DESCRIPTION
**Pull request by carlinmack**
Fixing issue 2 of #72

### CODE REVIEW

**Comment by b-g** [comment]
Hi @carlinmack, many thanks for this! + Much appreciated! Just the files seem to be broken:

Screen Shot 2019-11-20 at 08 49 52
Screen Shot 2019-11-20 at 08 52 14

Side note: As they pass unfortunately the https://openmoji-tester.glitch.me/ app in "green" ... I will have to once more beef up the openmoji-tester app :(

**Comment by carlinmack** [comment]
I noticed that the rich diff didn't show but I was confused why not, as they do display properly in inkscape if you copy the raw text. I'll submit another commit that removes the duplicate attribute.

If it's because of duplicate attributes it shouldn't be too hard to detect them, I might even have a go at implementing this.

**Comment by carlinmack** [comment]
@b-g how can I run file-format.js locally?

**Comment by b-g** [comment]
@carlinmack 

> How can I run file-format.js locally?

```
node_modules/.bin/mocha --grep "layer existing" --reporter mochawesome --reporter-options reportDir=test/report,reportFilename=report,json=false,code=false,cdn=true,reportTitle=OpenMoji-Tester,reportPageTitle=OpenMoji-Tester test/*.js --openmoji-data-json $PWD/data/openmoji.json --openmoji-src-folder $PWD/src
```

or better use the https://github.com/hfg-gmuend/openmoji-tester repo to develop tests ... there you can run a test on a single svg file

**Comment by b-g** [comment]
@carlinmack 

Had a quick chat with @dnlutz on your contribution! Really better! Just we think that having the eyes that detailed is too much. We aim for minimalism and this would introduce another special case. Sorry! I hope you understand our point of view!

Could you?
- Eyes with circles only
- Add changes to changelog

Happy to merge it afterwards.

Thanks!!

**Comment by carlinmack** [comment]
sure!

**Comment by b-g** [comment]
@carlinmack Thanks! Merged!

**Pull request merged**
