### PR TITLE
Improve feet

### PR DESCRIPTION
**Pull request by carlinmack**
#72 

@dnlutz thoughts? before isn't even recognisably feet

### CODE REVIEW

**Comment by dnlutz** [comment]
hello @carlinmack which foot are you refering to? 
sorry, but github ist sometimes still a bit confusing for me ; )

i would suggest to use a more geometric foot then it fits better to the other openmoji.
geometric_foot

**Comment by carlinmack** [comment]
If you click on "Files Changed" at the top and click this button

image

**Comment by b-g** [comment]
Thanks! This PR seems redundant with https://github.com/hfg-gmuend/openmoji/commit/4920b030bb17c312e0bc30dd720c95f6d8c4385f. Not merged and closed. Hope this is fine for everyone.

**Comment by carlinmack** [comment]
Can we please review what commits do before closing them? This commit deals with 1F**463** not 1F**9B6**

Please re-review this, thanks

**Comment by b-g** [comment]
Hi @carlinmack, I'm really sorry! ❤️ I crossed wires and thought I've had already reviewed it. My apologies! Yes ... it is a nice improved! Merged! 🙏

**Pull request merged**
