### PR TITLE
adding web syndication symbol

### PR DESCRIPTION
**Pull request by fuddl**
refs #183

### CODE REVIEW

**Comment by carlinmack** [comment]
this appears to be the old version with the wrong spacing 
image

**Comment by fuddl** [comment]
🤦‍♂️

**Comment by fuddl** [comment]
as it turns out `stroke-alignment="center"` can't be exported:
 stroke-alignment

probably because no browser supports it yet 😅

**Comment by carlinmack** [comment]
I think that just refers to where the stroke itself is drawn

image

 I feel like the centering we're talking about is positional and should be supported?

**Comment by fuddl** [comment]
fixed

**Pull request merged**
