### PR TITLE
moving esperanto to 🏳️‍🟩‍⭐‍🟩

### PR DESCRIPTION
**Pull request by fuddl**
refs #199

### CODE REVIEW

**Comment by carlinmack** [comment]
It's okay for this commit but before making PRs in the future can you please `git checkout master` and `git pull`

image

**Comment by fuddl** [comment]
outch, i see. Wait I'll try a cherry pick

**Comment by carlinmack** [comment]
image
file names are case sensitive

**Comment by carlinmack** [comment]
please don't change anything, just learn for future PRs! 👍

**Comment by carlinmack** [comment]
btw if you are having trouble with merge conflicts I would recommend (pulling with rebase)[https://coderwall.com/p/7aymfa/please-oh-please-use-git-pull-rebase] I've even (set it as my default)[https://stackoverflow.com/questions/13846300/how-to-make-git-pull-use-rebase-by-default-for-all-my-repositories] :)

**Comment by carlinmack** [comment]
No!!!!

**Comment by carlinmack** [comment]
Please don't force push without checking what you will be overwriting

**Comment by fuddl** [comment]
> No!!!!

whats wrong?

**Comment by carlinmack** [comment]
image
I had just pushed this with all checks passing

**Comment by fuddl** [comment]
😅 sorry

**Comment by carlinmack** [comment]
Yeah you basically just reverted my two commits oops,

To be clear, I am now going to force push from my branch so that the checks can pass and this can be merged

**Comment by carlinmack** [comment]
No problem, just make sure what the status of remote is before you overwrite

**Pull request merged**
