### PR TITLE
Fix heights of fingers to make them all the same height

### PR DESCRIPTION
**Pull request by carlinmack**
The welcome emoji we use on the front page has bugged me for awhile. I hope you can see the difference and agree with me. After discussion can you create the new file and update the README.md?

### CODE REVIEW

**Comment by carlinmack** [comment]
very difficult to see in the files changed tab, for clarity

Before:
image
After:
image
biggest change is little finger, all (including thumb) were changed except for ring finger which I used as the template

**Comment by b-g** [comment]
@carlinmack Ok + convinced! Looks better! Thanks for spotting and improving! Merged. Can you add your improvements to the changelog.txt?

**Comment by carlinmack** [comment]
Fix their fingers please! I'm not sure how to export to png
image

**Comment by b-g** [comment]
Will do! :)

github-keyvisual

**Comment by b-g** [comment]
Done :)

**Comment by carlinmack** [comment]
😁

**Pull request merged**
