### PR TITLE
Let's go: Golang

### PR DESCRIPTION
**Pull request by xavizardKnight**
Let's talk about the Golang icon.

I've pushed 5 versions of the Golang icon on the /src/ folder. These are just tests, and the final emoji will be moved to the correct place when finished.

The original emoji that I presented in PR #495 is `golang-smaller.svg`. `golang-bigger.svg` is the same, but bigger (following your suggestion on the original PR of making the letters bigger). `golang-blue-smaller.svg` and `golang-blue-bigger.svg` are the same as the non-blue ones, but without the black outline at the GO letters. `golang-original.svg` is using the letters of the original logo instead of the OpenMoji font. The original has a line between the G and O, but I think removing it is better in this case.

Which one do you prefer the most? You should have read and write access to this branch, so feel free to experiment how you wish.

Once we decide on a version, I'll rename it, move it to the correct place, remove the others and readd the metadata.

Related with issue #468 and PR #495.

### CODE REVIEW

**Comment by dnlutz** [comment]
My favourite is golang-original.svg. It looks more dynamic than the upright OpenMoji letters so I would suggest to go for this one. Thank you!

**Comment by b-g** [comment]
I agree with Daniel ... but @xavizardKnight what do you think?

**Comment by b-g** [comment]
And many thanks for taking the time to prepare five versions! 👍 🙏

**Comment by xavizardKnight** [comment]
Hi! Sorry for the super delay that I'm replying lately; I'm having a complicated year.

I agree that the version with the original lettering style looks better than the rest. Although it does look weird (at least for me) for an icon with such big letters to not use the OpenMoji font…

I'll start to tidy up this branch to prepare the original lettering style emoji to merge it soon. Will ping when everything's ready!

**Comment by b-g** [comment]
Great! Hope all is good on your end! Yes ... this will be a special case :)

**Comment by b-g** [comment]
@xavizardKnight That's great! Many thanks! + Merged.

**Pull request merged**
