### PR TITLE
ISO codes for country flags

### LINKED ISSUE #234: Colorless flag emojis: use ISO country codes
Currently, the country flags appear blank without color and are indistinguishable.  
I propose to include the [ISO country code letters](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) for the no-color version via the `line-supplement` layer.

blank flag

### PR DESCRIPTION
**Pull request by eltos**
Adds ISO country codes to black style flags via `line-supplement`

- [x] Test Your Design (random sample)
- [ ] Normalize SVG Formatting

Some examples:
|         |AC|AD|AE|AF|AG|AI|AL|AM
|---------|-|-|-|-|-|-|-|-|
| color   |1F1E6-1F1E8|1F1E6-1F1E9|1F1E6-1F1EA|1F1E6-1F1EB|1F1E6-1F1EC|1F1E6-1F1EE|1F1E6-1F1F1|1F1E6-1F1F2|
| black (before)  |1F1E6-1F1E8|1F1E6-1F1E9|1F1E6-1F1EA|1F1E6-1F1EB|1F1E6-1F1EC|1F1E6-1F1EE|1F1E6-1F1F1|1F1E6-1F1F2|
|         |⬇️|⬇️|⬇️|⬇️|⬇️|⬇️|⬇️|⬇️|
| black (after)   |1F1E6-1F1E8|1F1E6-1F1E9|1F1E6-1F1EA|1F1E6-1F1EB|1F1E6-1F1EC|1F1E6-1F1EE|1F1E6-1F1F1|1F1E6-1F1F2|

closes #234

### CODE REVIEW

**Comment by eltos** [comment]
@b-g can you (or someone else) please take care of prettifying the SVG formatting? Tank you :)

**Comment by b-g** [comment]
Hi @eltos! Wow that was quick! Very nice "hack" to use the `line-supplement` layer to add the country codes only on the exported black production files! 

Comments:
- It seems to be the convention that the letters sit inside a dashed rectangle. Could you share some variant sketches to check how to represent this better? See https://en.wikipedia.org/wiki/Regional_Indicator_Symbol#Unicode_block https://www.unicode.org/charts/PDF/U1F100.pdf

Screen Shot 2020-05-27 at 14 38 50
 
- Could you also share you generator script? The spacing of the letter seems to be slightly too wide from a typographic point of view. Would be good to get that as perfect as possible.

cc @dnlutz please check the spacing and provide feedback if necessary. THX

**Comment by eltos** [comment]
Hi @b-g,

to your comments:
- In my opinion dashed lines do not give a benefit, neither will they look good with stroke widths of 2px as per the style guide. Citing the unicode PDF you linked: 
  >  In some emoji implementations, certain pairs may be recognized and displayed by alternate means

  So I guess this covers the "alternate means" case.
- The letters are centered around two points placed symmetrically on either side of the flags center. Typographically correct spacing would require a dynamic adjustment based on the individual letters. I am no typographical expert and don't think I can implement this correctly. Please find my script below.

PS: the "hack" is described in the [style guide on your projects website](https://openmoji.org/styleguide/#submission). I just followed this guide :)

--------

<details><summary>Python script that adds ISO country codes to flags (click to show)</summary>

````python
#!/usr/bin/env python3

import os


# SVG letter definitions
#########################

# taken from guidelines/openmoji-abc.svg and centered
SVG = {
'A': '<path transform="translate(16.33 9.97)" d="m0 7-3-7-3 7"/>'
  +'\n<path transform="translate(11.33 15.29)" d="m0 0h4"/>'
,'B': '<path transform="translate(14 9.97)" d="m0 3.487h-2.669v-3.487h2.669c0.963 0 1.744 0.781 1.744 1.744s-0.781 1.743-1.744 1.743z"/>'
   +'\n<path transform="translate(14 13.46)" d="m0 3.487h-2.669v-3.487h2.669c0.963 0 1.744 0.78 1.744 1.743s-0.781 1.744-1.744 1.744z"/>'
,'C': '<path transform="translate(15 10.6)" d="m0 5.742c-0.441 0.391-1.022 0.629-1.659 0.629-1.38 0-2.5-1.119-2.5-2.5v-2 2-2c0-1.381 1.12-2.5 2.5-2.5 0.637 0 1.218 0.238 1.659 0.629"/>'
,'D': '<path transform="translate(13.5 9.97)" d="m0 6.974h-2.427v-6.974h2.427c1.148 0 2.08 0.931 2.08 2.079v2.815c0 1.149-0.932 2.08-2.08 2.08z"/>'
,'E': '<path transform="translate(15 16.97)" d="m0-7h-4v7h4"/>'
   +'\n<path transform="translate(11 13.47)" d="m0 0h3"/>'   
,'F': '<path transform="matrix(-1 0 0 1 12 13.47)" d="m-2 0h3v3.5-7h-4"/>'
,'G': '<path transform="translate(15 16.34)" d="m0-5.742c-0.441-0.392-1.022-0.629-1.659-0.629-1.38 0-2.5 1.119-2.5 2.5v2c0 1.38 1.12 2.5 2.5 2.5 1.381 0 2.5-1.12 2.5-2.5v-1.014h-2"/>'
,'H': '<path transform="matrix(0 1 1 0 15 13.47)" d="m-3.5-3.5h7"/>'
   +'\n<path transform="matrix(0 1 1 0 19 13.47)" d="m-3.5-3.5h7"/>'
   +'\n<path transform="matrix(-1 0 0 1 11.5 13.46)" d="m-4 0h4"/>'
,'I': '<path transform="matrix(0 1 1 0 16.5 13.47)" d="m-3.5-3.5h7"/>'
,'J': '<path transform="translate(15 16.97)" d="m0-7v4.5c0 1.381-1.119 2.5-2.5 2.5-0.643 0-1.229-0.243-1.673-0.642"/>'
,'K': '<path transform="matrix(0 1 1 0 14.8 13.47)" d="m-3.5-3.5h7"/>'
   +'\n<path transform="matrix(.6612 -.7502 -.7502 -.6612 13.7 15.24)" d="m-1.025 2.27h6.05"/>'
   +'\n<path transform="matrix(.4584 .8888 .8888 -.4584 16 12.52)" d="m-1.416-2.323h5.228"/>'
,'L': '<path transform="translate(11.8 16.97)" d="m0-7v7h3"/>'
,'M': '<path transform="matrix(0 -1 -1 0 17 10.47)" d="m-6.5 0.5h7l-6 3 6 3h-7"/>'
,'N': '<path transform="translate(11 9.97)" d="m0 7v-7l5 7v-7"/>'
,'O': '<path transform="translate(13.2 9.97)" d="m0 7c-1.38 0-2.5-1.119-2.5-2.5v-2c0-1.381 1.12-2.5 2.5-2.5 1.381 0 2.5 1.119 2.5 2.5v2c0 1.381-1.119 2.5-2.5 2.5z"/>'
,'P': '<path transform="translate(11.5 9.97)" d="m0 7v-7h2.669c0.963 0 1.744 0.781 1.744 1.744s-0.781 1.743-1.744 1.743h-2.669"/>'
,'Q': '<path transform="translate(13.2 9.97)" d="m0 7c-1.38 0-2.5-1.119-2.5-2.5v-2c0-1.381 1.12-2.5 2.5-2.5 1.381 0 2.5 1.119 2.5 2.5v2c0 1.381-1.119 2.5-2.5 2.5z"/>'
   +'\n<path transform="translate(14 16.97)" d="M0,-1.676L1.688,0L0,-1.676Z"/>'
,'R': '<path transform="translate(11 9.97)" d="m0 7v-7h2.669c0.963 0 1.744 0.781 1.744 1.744s-0.781 1.743-1.744 1.743h-2.669"/>'
   +'\n<path transform="matrix(.3964 .9181 .9181 -.3964 15.8 13.82)" d="m-1.155-1.757 3.827 1e-3"/>'
,'S': '<path transform="translate(15 15.57)" d="m0-4.212c-0.205-0.798-1.091-1.397-2.153-1.397-1.214 0-2.198 0.783-2.198 1.75 0 0.966 0.984 1.75 2.198 1.75l-0.045 6e-3c1.214 0 2.198 0.784 2.198 1.75 0 0.967-0.984 1.75-2.198 1.75-1.062 0-1.948-0.6-2.153-1.398"/>'
,'T': '<path transform="translate(11 9.97)" d="m0 0h4"/>'
   +'\n<path transform="matrix(0 1 1 0 16.5 13.47)" d="m-3.5-3.5h7"/>'
,'U': '<path transform="matrix(0 1 1 0 17 15.97)" d="m-6-1h4.5c1.381 0 2.5-1.119 2.5-2.5 0-1.38-1.119-2.5-2.5-2.5h-4.5"/>'
,'V': '<path transform="translate(15 16.97)" d="m0-7-2 7-2-7"/>'
,'W': '<path transform="matrix(-.2747 .9615 .9615 .2747 15.6 18.28)" d="m-8.464-0.615h7.28l-6.181-3.847h7.28l-6.181-3.846"/>'
,'X': '<path transform="matrix(.4961 .8682 .8682 -.4961 15 10)" d="m-2.031-3.5h8.062"/>'
   +'\n<path transform="matrix(-.4961 .8682 .8682 .4961 15 16.94)" d="m-6.031-3.5h8.062"/>'
,'Y': '<path transform="matrix(0 -1 -1 0 17 13.47)" d="m-3.5 3.5h3l4-2-4 2 4 2"/>'
,'Z': '<path transform="translate(11 16.97)" d="m0-7h4l-4 7h4"/>'   
}

for i in SVG:
    # apply letter style
    SVG[i] = SVG[i].replace('/>', ' stroke-width="2px" stroke="#000" stroke-miterlimit="10" fill="none" stroke-linecap="round" stroke-linejoin="round"/>')
    
    # scale letters and move to left/right so two letters can be combined
    SVG[i] = (SVG[i].replace('transform="', 'transform="scale(2.7, 2.7) translate(-5.3, 0) '),  # 1st letter 
              SVG[i].replace('transform="', 'transform="scale(2.7, 2.7) translate(+5.3, 0) '),  # 2nd letter
              )



# modify flags
################

dir = 'src/flags/country-flag'

for file in os.listdir(dir):
    # extract code points from filename like '1F1E8-1F1EB.svg'
    codes = [int(s, 16) for s in file[:-4].split('-')]
    ISO = ''.join([chr(65 + code - 0x1f1e6) for code in codes]) # two letter ISO country code
       
    # construct SVG snipped to insert
    path = '\n'.join([SVG[ISO[i]][i] for i in range(len(ISO))])
    line_supplement = '  <g id="line-supplement">\n    ' + '\n    '.join(path.split('\n')) + '\n  </g>'
    
    # insert snipped in file
    raw = open(os.path.join(dir, file)).read()
    raw = raw.replace('  <g id="color">', line_supplement + '\n' + '  <g id="color">')  # insert before color group
    open(os.path.join(dir, file), 'w').write(raw)
    
    print(file, ISO)

print('Note: The flags of Switzerland (1F1E8-1F1ED.svg), Vatican City (1F1FB-1F1E6.svg) and Nepal (1F1F3-1F1F5.svg) have a different shape. They require manual adjustments.')

```

</details>

**Comment by carlinmack** [comment]
maybe a solution would be to group the letters into widths (m width, n width), kern for those groups and then place the first letter appropriately - as the second will be in the middle. Does this sound reasonable?

**Comment by b-g** [comment]
Hi @eltos! Sorry for the long inactivity ... we are extra busy at the end of the semester. I gave you script a try and tweaked the parameters a bit. I think it looks better know ... but still IMO not good enough. Please see my tweaked script and the results.

Hence I would vote to drop the brute force approach and do it "properly" (or either leave it):
- refactor the script with node.js and jsDom, see scripts in `test` folder
- measure the bounding box of each letter, see [SVGGraphicsElement.getBBox()](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox)
- have a fixed space between the two letters
- center the g of both letters

What do you think?

--------

Screenshot 2020-06-30 at 13 44 11
Screenshot 2020-06-30 at 13 44 33
Screenshot 2020-06-30 at 13 44 46


--------

<details><summary>Python script that adds ISO country codes to flags (click to show)</summary>

```python
#!/usr/bin/env python

import os


# SVG letter definitions
#########################

# taken from guidelines/openmoji-abc.svg and centered
SVG = {
'A': '<path transform="translate(16.33 9.97)" d="m0 7-3-7-3 7"/>'
  +'\n<path transform="translate(11.33 15.29)" d="m0 0h4"/>'
,'B': '<path transform="translate(14 9.97)" d="m0 3.487h-2.669v-3.487h2.669c0.963 0 1.744 0.781 1.744 1.744s-0.781 1.743-1.744 1.743z"/>'
   +'\n<path transform="translate(14 13.46)" d="m0 3.487h-2.669v-3.487h2.669c0.963 0 1.744 0.78 1.744 1.743s-0.781 1.744-1.744 1.744z"/>'
,'C': '<path transform="translate(15 10.6)" d="m0 5.742c-0.441 0.391-1.022 0.629-1.659 0.629-1.38 0-2.5-1.119-2.5-2.5v-2 2-2c0-1.381 1.12-2.5 2.5-2.5 0.637 0 1.218 0.238 1.659 0.629"/>'
,'D': '<path transform="translate(13.5 9.97)" d="m0 6.974h-2.427v-6.974h2.427c1.148 0 2.08 0.931 2.08 2.079v2.815c0 1.149-0.932 2.08-2.08 2.08z"/>'
,'E': '<path transform="translate(15 16.97)" d="m0-7h-4v7h4"/>'
   +'\n<path transform="translate(11 13.47)" d="m0 0h3"/>'
,'F': '<path transform="matrix(-1 0 0 1 12 13.47)" d="m-2 0h3v3.5-7h-4"/>'
,'G': '<path transform="translate(15 16.34)" d="m0-5.742c-0.441-0.392-1.022-0.629-1.659-0.629-1.38 0-2.5 1.119-2.5 2.5v2c0 1.38 1.12 2.5 2.5 2.5 1.381 0 2.5-1.12 2.5-2.5v-1.014h-2"/>'
,'H': '<path transform="matrix(0 1 1 0 15 13.47)" d="m-3.5-3.5h7"/>'
   +'\n<path transform="matrix(0 1 1 0 19 13.47)" d="m-3.5-3.5h7"/>'
   +'\n<path transform="matrix(-1 0 0 1 11.5 13.46)" d="m-4 0h4"/>'
,'I': '<path transform="matrix(0 1 1 0 16.5 13.47)" d="m-3.5-3.5h7"/>'
,'J': '<path transform="translate(15 16.97)" d="m0-7v4.5c0 1.381-1.119 2.5-2.5 2.5-0.643 0-1.229-0.243-1.673-0.642"/>'
,'K': '<path transform="matrix(0 1 1 0 14.8 13.47)" d="m-3.5-3.5h7"/>'
   +'\n<path transform="matrix(.6612 -.7502 -.7502 -.6612 13.7 15.24)" d="m-1.025 2.27h6.05"/>'
   +'\n<path transform="matrix(.4584 .8888 .8888 -.4584 16 12.52)" d="m-1.416-2.323h5.228"/>'
,'L': '<path transform="translate(11.8 16.97)" d="m0-7v7h3"/>'
,'M': '<path transform="matrix(0 -1 -1 0 17 10.47)" d="m-6.5 0.5h7l-6 3 6 3h-7"/>'
,'N': '<path transform="translate(11 9.97)" d="m0 7v-7l5 7v-7"/>'
,'O': '<path transform="translate(13.2 9.97)" d="m0 7c-1.38 0-2.5-1.119-2.5-2.5v-2c0-1.381 1.12-2.5 2.5-2.5 1.381 0 2.5 1.119 2.5 2.5v2c0 1.381-1.119 2.5-2.5 2.5z"/>'
,'P': '<path transform="translate(11.5 9.97)" d="m0 7v-7h2.669c0.963 0 1.744 0.781 1.744 1.744s-0.781 1.743-1.744 1.743h-2.669"/>'
,'Q': '<path transform="translate(13.2 9.97)" d="m0 7c-1.38 0-2.5-1.119-2.5-2.5v-2c0-1.381 1.12-2.5 2.5-2.5 1.381 0 2.5 1.119 2.5 2.5v2c0 1.381-1.119 2.5-2.5 2.5z"/>'
   +'\n<path transform="translate(14 16.97)" d="M0,-1.676L1.688,0L0,-1.676Z"/>'
,'R': '<path transform="translate(11 9.97)" d="m0 7v-7h2.669c0.963 0 1.744 0.781 1.744 1.744s-0.781 1.743-1.744 1.743h-2.669"/>'
   +'\n<path transform="matrix(.3964 .9181 .9181 -.3964 15.8 13.82)" d="m-1.155-1.757 3.827 1e-3"/>'
,'S': '<path transform="translate(15 15.57)" d="m0-4.212c-0.205-0.798-1.091-1.397-2.153-1.397-1.214 0-2.198 0.783-2.198 1.75 0 0.966 0.984 1.75 2.198 1.75l-0.045 6e-3c1.214 0 2.198 0.784 2.198 1.75 0 0.967-0.984 1.75-2.198 1.75-1.062 0-1.948-0.6-2.153-1.398"/>'
,'T': '<path transform="translate(11 9.97)" d="m0 0h4"/>'
   +'\n<path transform="matrix(0 1 1 0 16.5 13.47)" d="m-3.5-3.5h7"/>'
,'U': '<path transform="matrix(0 1 1 0 17 15.97)" d="m-6-1h4.5c1.381 0 2.5-1.119 2.5-2.5 0-1.38-1.119-2.5-2.5-2.5h-4.5"/>'
,'V': '<path transform="translate(15 16.97)" d="m0-7-2 7-2-7"/>'
,'W': '<path transform="matrix(-.2747 .9615 .9615 .2747 15.6 18.28)" d="m-8.464-0.615h7.28l-6.181-3.847h7.28l-6.181-3.846"/>'
,'X': '<path transform="matrix(.4961 .8682 .8682 -.4961 15 10)" d="m-2.031-3.5h8.062"/>'
   +'\n<path transform="matrix(-.4961 .8682 .8682 .4961 15 16.94)" d="m-6.031-3.5h8.062"/>'
,'Y': '<path transform="matrix(0 -1 -1 0 17 13.47)" d="m-3.5 3.5h3l4-2-4 2 4 2"/>'
,'Z': '<path transform="translate(11 16.97)" d="m0-7h4l-4 7h4"/>'
}

for i in SVG:
    # apply letter style
    SVG[i] = SVG[i].replace('/>', ' stroke-width="1.5px" stroke="#000" stroke-miterlimit="10" fill="none" stroke-linecap="round" stroke-linejoin="round"/>')

    # scale letters and move to left/right so two letters can be combined
    SVG[i] = (SVG[i].replace('transform="', 'transform="scale(2.5, 2.5) translate(-4, 0) '),  # 1st letter
              SVG[i].replace('transform="', 'transform="scale(2.5, 2.5) translate(4, 0) '),  # 2nd letter
              )



# modify flags
################

dir = 'src/flags/country-flag'

for file in os.listdir(dir):
    # extract code points from filename like '1F1E8-1F1EB.svg'
    codes = [int(s, 16) for s in file[:-4].split('-')]
    ISO = ''.join([chr(65 + code - 0x1f1e6) for code in codes]) # two letter ISO country code

    # construct SVG snipped to insert
    path = '\n'.join([SVG[ISO[i]][i] for i in range(len(ISO))])
    line_supplement = '  <g id="line-supplement" transform="translate(3.5, 2.5)">\n    ' + '\n    '.join(path.split('\n')) + '\n  </g>'

    # insert snipped in file
    raw = open(os.path.join(dir, file)).read()
    raw = raw.replace('  <g id="color">', line_supplement + '\n' + '  <g id="color" display="none">')  # insert before color group
    open(os.path.join(dir, file), 'w').write(raw)

    print(file, ISO)

print('Note: The flags of Switzerland (1F1E8-1F1ED.svg), Vatican City (1F1FB-1F1E6.svg) and Nepal (1F1F3-1F1F5.svg) have a different shape. They require manual adjustments. Also check: 1F1F2-1F1FC')


```

</details>

**Comment by carlinmack** [comment]
can we not just generate them naively then tweak them manually until they're ready, or is that what you're suggesting?

**Comment by b-g** [comment]
I think manually tweaking is not an option as we have 200+ flags. 

I'm suggesting basically either:

- not to have this feature as currently the quality (from a typographic point of view) is not good enough 
- or to do it properly as outline above

**Comment by carlinmack** [comment]
oh I see, that makes sense 👍 I think that proper way isn't too labour intensive

**Comment by b-g** [comment]
Closed due to inactivity. Please re-open if you want to give it another try :)

**Pull request closed without merging**
