### PR TITLE
August 2024 updated apple logo🛟

### PR DESCRIPTION
**Pull request by nataliakeniganti**
Updated brand-emoji for the apple logo.
The original looks like this:
image

### CODE REVIEW

**Comment by b-g** [comment]
Hi @nataliakeniganti, many thanks for this! We are back from the break. Happy to merge this ... but as an alternative. Please provide a new PR not touching the existing Apple logo and move the black one to hexcode `E06E`. Also there seems to be a small glitch, please fix as well. Happy to merge after. Cheers 👍 
Screen Shot 2024-10-01 at 16 03 54

**Comment by nataliakeniganti** [comment]
@b-g may be ask unclosed?

**Comment by nataliakeniganti** [comment]
> Hi @nataliakeniganti, many thanks for this! We are back from the break. Happy to merge this ... but as an alternative. Please provide a new PR not touching the existing Apple logo and move the black one to hexcode `E06E`. Also there seems to be a small glitch, please fix as well. Happy to merge after. Cheers 👍 Screen Shot 2024-10-01 at 16 03 54

Fixed it
F8FF

**Comment by b-g** [comment]
Nope. Still glitchy. I closed the PR as I would prefer a new one without all the noise. I hope you don't mind.

PS. Heads up: Will be working in the next days on all constantly as I have a limited time window. If you plan to contribute, please pull frequently and be aware that a few things might have become obsolete in PR as already addressed. 

Screen Shot 2024-10-02 at 08 13 47

**Comment by nataliakeniganti** [comment]
> Nope. Still glitchy. I closed the PR as I would prefer a new one without all the noise. I hope you don't mind.
> 
> PS. Heads up: Will be working in the next days on all constantly as I have a limited time window. If you plan to contribute, please pull frequently and be aware that a few things might have become obsolete in PR as already addressed.
> 
> Screen Shot 2024-10-02 at 08 13 47

Removed More Glitches
F8FF

**Comment by b-g** [comment]
Thanks. Looks better without the glitches. I've tested the file ... please use https://openmoji-tester.glitch.me/ ... quite some red lights. Won't be able to merge this without having the nitty gritty details right. Sorry!

**Comment by nataliakeniganti** [comment]
> Thanks. Looks better without the glitches. I've tested the file ... please use https://openmoji-tester.glitch.me/ ... quite some red lights. Won't be able to merge this without having the nitty gritty details right. Sorry!

btw removed glitches

**Comment by b-g** [comment]
Let know once the logo is fixed and passed the tests. Happy to add it then to the library.

**Pull request closed without merging**
