### PR TITLE
Added Pokeball emoji

### PR DESCRIPTION
**Pull request by inferno986return**

### CODE REVIEW

**Comment by b-g** [comment]
@inferno986return Nice! But could you add your meta infos to `data/extras-openmoji.csv` and run afterwards `npm run generate-data-tables`? That way your file is tested and ready to go.

**Comment by b-g** [comment]
Many thanks! Please:

1. `npm run generate-data-tables`
2. `npm run test-dev`

which will result in some errors ... please fix :) Afterwards happy to merge.

```
  1) Data integrity openmoji.json
       Hexcode and emoji property matches in openmoji.json?
          E157 property should be matching:

      AssertionError: expected 'E157' to equal 'E156'
      + expected - actual

      -E157
      +E156
      
      at Context.<anonymous> (test/data.js:30:44)

  2) OpenMoji file format
       SVG element id is named "emoji"?
          E157.svg SVG element should have an id named "emoji":
     AssertionError: expected null to equal 'emoji'
      at Context.<anonymous> (test/file-format.js:47:45)

  3) OpenMoji file format
       All basic shapes (rect, circle, line etc) without a style attribute?
          E157.svg should not contain basic shapes with a style attribute:

      AssertionError: expected 5 to equal 0
      + expected - actual

      -5
      +0
      
      at Context.<anonymous> (test/file-format.js:66:56)

  4) OpenMoji file format
       SVG has only <g> elements (layers) at top level?
          E157.svg should only have <g> elements at top level and no other elements:

      AssertionError: expected 1 to be at least 3
      + expected - actual

      -1
      +3
      
      at Context.<anonymous> (test/file-format.js:86:42)

  5) Layers
       #line layer existing?
          E157.svg should have a single #line layer:

      AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (test/layer.js:19:59)

  6) Layers
       #color layer existing?
          E157.svg should have a single #color layer:

      AssertionError: expected 0 to equal 1
      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (test/layer.js:28:60)
```

**Comment by inferno986return** [comment]
I have been trying to run these tests today using both npm on Ubuntu WSL and the native Windows package of Node.js. Both have errors.

Also do I need to include the template lines in the .svg or can I leave them out?

**Comment by b-g** [comment]
Many thanks! But this is not getting better. Please use https://openmoji-tester.glitch.me/ to fix all red tests. (You don't have to install anything). 

Can then take care of the rest. Cheers.

**Comment by b-g** [comment]
Closing due to inactivity. Sorry! Please re-open if you want to give it another go :)

**Pull request closed without merging**
