### PR TITLE
Switching Antarctic flag emoji to True South flag

### LINKED ISSUE #327: Potential Antarctic Flag Emoji
Hey Openmoji community,

I have a potentially complicated question regarding the Antarctic flag emoji that I'd love to have your input on.

Here are the basics:
- The Antarctic flag emoji (🇦🇶) appears as a light blue flag with a white silhouette on all supported platforms.
- **This design has no official status whatsoever.** It was simply the most popular of dozens of unofficial proposals at the time of emoji's creation.
- True South, an Antarctic flag proposed last year, is **the first and only Antarctic flag with official designation**. It has been formally adopted by national Antarctic programs, expedition teams, and other Antarctic organizations from around the world.

Those of us behind the flag plan to approach Unicode and other emoji providers to notify them of the new flag's status. While we anticipate this will lead to a change in their emoji design, we also anticipate this will be a long and difficult process. OpenMoji was created in response to the restrictive, bureaucratic system we're trying to navigate, which is exactly why we're reaching out. We'd be honored to have OpenMoji be the first emoji system to feature the True South design for the 1F1E6+1F1F6 designation.

You can find more information on the new flag and the old proposals on [the Wikipedia page](https://en.wikipedia.org/w/index.php?title=Flag_of_Antarctica&type=revision&diff=1028760400&oldid=1028760277). 

Thanks in advance for your input!

### PR DESCRIPTION
**Pull request by SpangleLabs**
This fixes #327 .
The Bartram flag currently in the emoji set is unofficial, while the [True South flag](https://en.wikipedia.org/wiki/Flag_of_Antarctica) is the only flag of Antarctica formally recognised.

I've used the correct flag colour here, [#1B2F4C](https://www.thecolorapi.com/id?hex=1b2f4c&format=html), instead of one from the openmoji pallette. The closest available in the pallette is [#1E50A0](https://www.thecolorapi.com/id?hex=1e50a0&format=html) but I'm not sure whether that is close enough?
I'm not certain the pallette protocol here when it comes to flags, to be honest.

### CODE REVIEW

**Comment by b-g** [comment]
Hi @SpangleLabs, many thank for this! 

We are happy to include the flag, but at the moment only a private use hexcode (see https://openmoji.org/library/#group=extras-openmoji%2Fflags) as IMO the flag is not fully recognized: 

> True South is the only flag of Antarctica formally recognized by members of the Antarctic Treaty System, the condominium that governs the continent.[1][2] However, adoption of the flag is not yet universal, and dozens of unofficial designs have also been proposed. 

In case I'm not up to date with the process, please provide links pointing to eg. Unicode or other official entities recognizing the flag.

OK? If so please:
- change the hexcode to private use
- fix the red tests

```
  2 failing

  1) Color
       Fill colors included in OpenMoji color palette?
         🇦🇶 1F1E6-1F1F6.svg should have correct fill colors:
     AssertionError: expected [ Array(32) ] to include '#1b2f4c'
      at /home/runner/work/openmoji/openmoji/test/color.js:31:34
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test/color.js:30:15)
      at processImmediate (internal/timers.js:464:21)

  2) Color
       Stroke colors included in OpenMoji color palette?
         🇦🇶 1F1E6-1F1F6.svg should have correct stroke colors:
     AssertionError: expected [ Array(32) ] to include '#1b2f4c'
      at /home/runner/work/openmoji/openmoji/test/color.js:43:34
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test/color.js:42:15)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by SpangleLabs** [comment]
Unicode does not officiate national flag designs (or indeed, nationhood). I thought that was the point of the flags being defined as [regional indicator characters](https://blog.emojipedia.org/emoji-flags-explained/)?
Unicode did not need to make a decision in order for [Mauritania to update their flag](https://emojipedia.org/flag-mauritania/) in 2017.

The current flag in the openmoji set for Antarctica, the Bartum flag, has never been made official. The True South flag has been recognised by various nations, as stated in your quote.
Here's a post about the Czech Antarctic Research Program recognising and supporting the flag:
https://www.truesouthflag.com/post/the-czech-antarctic-research-programme-joins-the-true-south-community

As I said, I wasn't sure the pallette rules for flags, I'll switch the colours to #1e50a0 to match the pallette

**Comment by AntarcticOcean** [comment]
@SpangleLabs This was recently confirmed by the Unicode emoji subcommittee chair. "Unicode does not specify the appearance of flag emoji. It is the responsibility of font designers to update their fonts as politics change." http://blog.unicode.org/2022/03/the-past-and-future-of-flag-emoji.html?m=1 @b-g

**Comment by carlinmack** [comment]
Hi I'm a long standing contributor to this project. One of our long-term goals has been to improve consistency with other emoji sets #72, #143. At current, every single emoji set is consistent on this flag. We encourage placing alternate designs in our OpenMoji Extras, including [flags](https://openmoji.org/library/#group=extras-openmoji%2Fflags). The benefits for having an emoji in this part of the library is that people can use this emoji in their projects immediately, and the designs can be swapped if the time comes. 

It gets a bit tricky if this project makes statements by recognising certain designs as official. For example, the process for designing the new Australian flag or New Zealand flag have resulted in public favourites, but it would be inappropriate to recognise any of them. I understand that this situation is different as there is some formal recognition, but I suggest that we wait until other emoji sets make the change before we promote it out of our extra section.

**Comment by SpangleLabs** [comment]
The recognition as official is kind of a non-argument, when the Bartram flag is official by zero means, and the True South flag is recognized by multiple states and entities. This isn't some flag referendum issue like NZ, where there was no official recognition of the proposed flags.

The argument about consistency with other sets does make sense though. I guess Openmoji doesn't want to be first mover in such a thing. I'm reminded of how the [dancer emoji](https://emojipedia.org/woman-dancing/) wasn't a woman in a red dress until Apple forced that change, and the [gun emoji](https://emojipedia.org/pistol/) became a water pistol under their stewardship.
However, neither of those have followed that standard in openmoji at all. So that might also need a fix

**Comment by b-g** [comment]
Hi there! I think all arguments have been exchanged. We - the project maintainer - can currently only offer to add the True South flag in openmoji-extras. If you want that, please rename the src svg file accordingly. If not, we hope you understand our stance as well and are not too disappointed. Sorry!

**Comment by SpangleLabs** [comment]
That's a shame. I'll get it moved to extras for now then, and open some issues for standardizing some other emoji.
I'm not certain the process, do I just need to move it to src/extras-unicode/flags? Or do I also need to update the various files in extras/?
I'm looking over [this PR](https://github.com/hfg-gmuend/openmoji/pull/212/files) for guidance.

**Comment by b-g** [comment]
You might find the infos in https://github.com/hfg-gmuend/openmoji/blob/master/CONTRIBUTING.md#octocat-non-standard-emoji helpful. 

Yes please move the scr files to extras-openmoji/flags/ e.g. E380.svg. or come up with a more meaningful hexcode combination, see the hexcodes of the other flags in https://openmoji.org/library/#group=extras-openmoji%2Fflags

Use the https://github.com/hfg-gmuend/openmoji-tester/ to make sure that all tests are "green"

I will then take care of the rest. Which name or org should be credited as the designer of the flag?

**Comment by SpangleLabs** [comment]
There we go, little messier git history than I would like, but that should be moved now!

I fixed a little typo I spotted too in the tags, though I guess technically HAL9000 is a rouge AI, but I suspect they meant rogue AI.

I've put down "Spangle Labs" as the name in the csv file. It's not a registered organisation or anything though. I could use my real name if you would prefer, but that name may change soon.

Sorry for the delay!

**Comment by b-g** [comment]
@SpangleLabs Many thanks! Merged

**Comment by SpangleLabs** [comment]
Thanks! Sorry about all the faff and delays

**Comment by SpangleLabs** [comment]
This whole situation came to mind again with a new video from CGP Grey about the Antarctic flag situation:
https://www.youtube.com/watch?v=U0wTDK0VOeY

Might be an interesting five minutes, but it raises the point that the Bartram flag was created for the 3D World Atlas video game, and as such, the copyright of it is unclear

**Pull request merged**
