### PR TITLE
Update Portuguese Flag

### PR DESCRIPTION
**Pull request by ferdinandsorg**
I got a mail from a portuguese guy, I did a mistake with the flag. So I changed it and in addition some improvements. Thanks to Francisco Maltez for this advice!

### CODE REVIEW

**Comment by carlinmack** [comment]
it is way more accurate now haha! I'm going to clean up the file before merging if that is okay, I don't think you exported the file with 
image
then ran `npm run pretty-src-svg`. It's okay though, I can save you the hassle :)

**Comment by ferdinandsorg** [comment]
hey @carlinmack thanks for the advice, I committed a new version of the svg. can you run this through the npm?

**Comment by carlinmack** [comment]
Hi, so I tried to do that and realised this:

image

It would now be easiest to:
```bash
git reset 815750e6 --hard 
git pull https://github.com/hfg-gmuend/openmoji.git master
git cherry-pick 791261eb ebaadc0d
git push https://github.com/ferdinandsorg/openmoji.git master
```

* reset git to the last common commit with hfg-gmuend
* fast forward to the current branch
* apply the two commits updating the portugese flag
* update your PR

**Comment by carlinmack** [comment]
I can still run pretty-src-svg as I have the file and this is the output:

```SVG
<svg id="emoji" viewBox="0 0 72 72" xmlns="http://www.w3.org/2000/svg">
  <g id="grid">
    <path fill="#b3b3b3" d="M68,4V68H4V4H68m4-4H0V72H72Z"/>
    <path fill="none" stroke="#00a5ff" stroke-miterlimit="10" stroke-width="0.1" d="M12.9,11H59.1A1.8987,1.8987,0,0,1,61,12.9h0V59a1.8987,1.8987,0,0,1-1.9,1.9H12.9A1.8371,1.8371,0,0,1,11,59h0V12.9A1.8987,1.8987,0,0,1,12.9,11Z"/>
    <path fill="none" stroke="#00a5ff" stroke-miterlimit="10" stroke-width="0.1" d="M18.3,4H53.8A2.2425,2.2425,0,0,1,56,6.3V65.8a2.3261,2.3261,0,0,1-2.3,2.3H18.3A2.4139,2.4139,0,0,1,16,65.7V6.3A2.263,2.263,0,0,1,18.3,4Z"/>
    <path fill="none" stroke="#00a5ff" stroke-miterlimit="10" stroke-width="0.1" d="M68,18.3V53.8a2.3261,2.3261,0,0,1-2.3,2.3H6.3A2.4139,2.4139,0,0,1,4,53.7V18.3A2.263,2.263,0,0,1,6.3,16H65.8A2.2425,2.2425,0,0,1,68,18.3Z"/>
    <circle cx="36" cy="36" r="29" fill="none" stroke="#00a5ff" stroke-miterlimit="10" stroke-width="0.1"/>
  </g>
  <g id="color">
    <rect x="5" y="17" width="62" height="38" fill="#d22f27"/>
    <rect x="5" y="17" width="21" height="38" fill="#5c9e31"/>
    <circle cx="26" cy="36" r="12" fill="none" stroke="#fcea2b" stroke-miterlimit="10" stroke-width="2"/>
    <line x1="26" x2="26" y1="24" y2="48" fill="none" stroke="#fcea2b" stroke-linecap="round" stroke-linejoin="round"/>
    <polygon fill="none" stroke="#fcea2b" stroke-linecap="round" stroke-linejoin="round" points="26 39.5 17 44 35 44 26 39.5"/>
    <polygon fill="none" stroke="#fcea2b" stroke-linecap="round" stroke-linejoin="round" points="26 33.5 35 28 26.5 29.5 17 28 26 33.5"/>
    <polygon fill="none" stroke="#fcea2b" stroke-linecap="round" stroke-linejoin="round" points="38 36 26 41 14 36 26 31 38 36"/>
    <path fill="#fff" stroke="#d22f27" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.2,29H31.8V39.1c0,2.5-2.6,4.6-5.8,4.6h0c-3.2,0-5.8-2.1-5.8-4.6V29Z"/>
    <circle cx="26" cy="32.8" r="0.7" fill="#1e50a0" stroke="#1e50a0" stroke-linecap="round" stroke-linejoin="round"/>
    <circle cx="26" cy="38.7" r="0.7" fill="#1e50a0" stroke="#1e50a0" stroke-linecap="round" stroke-linejoin="round"/>
    <circle cx="26" cy="35.7" r="0.7" fill="#1e50a0" stroke="#1e50a0" stroke-linecap="round" stroke-linejoin="round"/>
    <circle cx="29" cy="35.7" r="0.7" fill="#1e50a0" stroke="#1e50a0" stroke-linecap="round" stroke-linejoin="round"/>
    <circle cx="23" cy="35.7" r="0.7" fill="#1e50a0" stroke="#1e50a0" stroke-linecap="round" stroke-linejoin="round"/>
  </g>
  <g id="line">
    <rect x="5" y="17" width="62" height="38" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"/>
  </g>
</svg>
```

feel free to add this as a third commit

**Comment by b-g** [comment]
Hi @ferdinandsorg, Many thanks for the fix! Let us know whether we should commit the final version or you. Problem is we can't add commits to your PR as it is only your branch. Sorry for the Github craziness. Stay healthy! B

**Comment by ferdinandsorg** [comment]
hey @carlinmack @b-g thanks for the support. I committed a third version with your (@carlinmack ) svg code. I lost the overview now with all this Github possibilities, I hope that's fine now!? Or do I need something else to do?
All the best to you!

**Comment by carlinmack** [comment]
can you please run this first?

```
git reset 815750e --hard 
git pull https://github.com/hfg-gmuend/openmoji.git master
git cherry-pick 791261e ebaadc0 cb369e0
git push https://github.com/ferdinandsorg/openmoji.git master
```

your branch is over 150 commits behind the master which is causing all the conflicts :(

**Comment by ferdinandsorg** [comment]
the cherry-pick fails, what am I doing wrong?
Screenshot 2020-03-23 at 14 19 32

**Comment by carlinmack** [comment]
```
git cherry-pick --abort
git reset 815750e --hard 
git pull https://github.com/hfg-gmuend/openmoji.git master
git cherry-pick 791261e ebaadc0 cb369e0
```

check no git errors! then `
git push https://github.com/ferdinandsorg/openmoji.git master -f`

**Comment by ferdinandsorg** [comment]
so that's it? thanks for your patience! I'm still learning how GitHub works...

**Comment by carlinmack** [comment]
image
I don't think the cherry-pick worked? I don't see your portugese flag commits, no worries!

**Comment by ferdinandsorg** [comment]
I either can't commit or pull...
Screenshot 2020-03-23 at 14 47 38

**Comment by carlinmack** [comment]
okay I think the only option rn is to `git cherry-pick --abort` and then make a new commit that changes the portugese flag to the final version, this should definitely work haha

**Comment by ferdinandsorg** [comment]
I just did a new pull request

**Pull request closed without merging**
