### PR TITLE
Build COLR TTFs with nanoemoji

### PR DESCRIPTION
**Pull request by mavit**
This is done via the container at https://gitlab.com/mavit/nanoemoji-container.

For me, the resulting COLR TTFs work in Firefox and in the Gnome desktop on Fedora 32 ~~(although they display rather small)~~.

Caveats:
- It may be premature to replace `scfbuild` for SVG builds.  If we decide to go ahead without `scfbuild`, then we’ll want to remove the remaining files related to it.  If we decide to keep `scfbuild`, then we’ll want to revert those parts of this patch.  In either case we’ll want to update the readme to link to the new outputs.
- I’ve tested this with Podman, not Docker.

Relates to #93.

### CODE REVIEW

**Comment by mavit** [comment]
Any feedback?

**Comment by carlinmack** [comment]
This is super cool! I think @b-g would be responsible for testing this with the other fonts. 

In the meantime, could you attach some screenshots? 

Thanks so much!

**Comment by mavit** [comment]
image
Screenshot from 2020-10-14 11-02-56
Screenshot from 2020-10-14 11-03-02

**Comment by carlinmack** [comment]
wow the quality is so much higher than we've ever had! Thank you for making them larger too, we still need to figure out what option we want to choose (#112 #257), but I think the size you have used is pretty good

**Comment by mavit** [comment]
I took the 1.3 scaling factor from d66343ea2cb92a33bb8f969b8eff0cc5976d4d70, although I think it looks a little cramped and would be tempted to go for something smaller.

**Comment by b-g** [comment]
Dear @mavit! This is mega! 

My apologies for the very long radio silence over the summer ... but I needed a break with the OpenMoji project :)

I totally would love to swap `scfbuild`with your version of `nanoemoji`! scfbuild is no longer actively maintained and this in contrast with a very active nanoemoji project (backed/funded by Google) makes at least for me the decision very easy.

I've tried to build the fonts with `npm run generate-font` but failed. It would be important that the colorfont generator stays accessible in terms complexity and operation systems. A lot of the people on the project are not coding experts but eventually need to generate the fonts. 

Could you check `./helpers/generate-fonts.sh: line 39: OpenMoji-${saturation^}: bad substitution` so that I could give it a try as well?

```console
bene@zwei-207 openmoji % npm run generate-font

> openmoji@12.4.0 generate-font /Users/bene/Documents/openmoji
> ./helpers/generate-fonts.sh

👉 generate-font-css.js
master: Pulling from mavit/nanoemoji-container
c7def56d621e: Pull complete 
f2931b91d78b: Pull complete 
f6b4b8ceb868: Pull complete 
Digest: sha256:77b71ae860417e531c72870d17128e878b87a8989479e7010073e607d04a937c
Status: Downloaded newer image for registry.gitlab.com/mavit/nanoemoji-container:master
registry.gitlab.com/mavit/nanoemoji-container:master
./helpers/generate-fonts.sh: line 39: OpenMoji-${saturation^}: bad substitution
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openmoji@12.4.0 generate-font: `./helpers/generate-fonts.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openmoji@12.4.0 generate-font script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bene/.npm/_logs/2020-10-15T07_18_22_557Z-debug.log
```

**Comment by mavit** [comment]
I'm guessing you're using MacOS, here, because it turns out that that has an ancient version of `bash` which doesn't support the `${variable^}` feature.  I'll move this substitution into the container, where we have a known version.

**Comment by carlinmack** [comment]
you should [shellcheck](https://www.shellcheck.net/) your bash scripts, it's helpful for catching stuff like this :)

**Comment by mavit** [comment]
> you should [shellcheck](https://www.shellcheck.net/) your bash scripts, it's helpful for catching stuff like this :)

This is good advice, but I do, and it doesn't help here: ShellCheck knows that `${variable^}` needs Bash, but we _are_ using Bash, so it doesn't warn.

**Comment by b-g** [comment]
Yes I'm on macOS, using zsh (note: 10.15 Cataline replaced bash with zsh).

```
% zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

Still the same error.

Yes would be great to move as much as possible inside a fully controlled docker image.

**Comment by mavit** [comment]
> Yes I'm on macOS, using zsh (note: 10.15 Cataline replaced bash with zsh).

`/bin/bash` will get used anyway, here, since that's what's specified on the `#!` line of the script.

> Still the same error.

Sorry, I overlooked a second place where this syntax was used.  Please try it again.

**Comment by b-g** [comment]
Many thanks for the recent fixes! I'm able to run it now!

First impression is good! Can't spot any difference if I use `demo.html`:

| scfbuild  | nanoemoji |
| ------------- | ------------- |
| Screen Shot 2020-10-16 at 12 22 09 | Screen Shot 2020-10-16 at 14 11 34 |

However if I'm using your generated demos I get some bugs (why?):
- Big color emojis are cropped
- Black notebook is broken 
- Black stroke weight is not always the same

Screen Shot 2020-10-16 at 14 03 57
Screen Shot 2020-10-16 at 14 04 17


Will also ask @dnlutz to import the files in a font editor to cross check everything ...

[OpenMoji-exported_nanoemoji.zip](https://github.com/hfg-gmuend/openmoji/files/5391469/OpenMoji-experted_nanoemoji.zip)


And it is worth pointing out that the font files have a massively smaller footprint in terms of files size:
- OpenMoji-Black.ttf 9.4 MB vs 1.4 MB
- OpenMoji-Color.ttf 13.6 MB vs 2.2 MB

This seems to almost magic :)

**Comment by mavit** [comment]
> However if I'm using your generated demos I get some bugs (why?):
> 
>     * Big color emojis are cropped
>     * Black notebook is broken

I don't see these issues in Firefox for Fedora Linux. I wonder if this is related to the capabilities of the OS's font rendering.  Are you using the SVG or the COLR/CPAL font, here?

Scaling the glyphs up to 130% causes them to overspill their bounding boxes, so, to be honest, I was surprised when I tried it and they didn't appear cropped for me.

>     * Black stroke weight is not always the same

I do see this issue.  I've tried building with `nanoemoji`'s `untouchedsvgz` format (edit line 50 of `generate-fonts.sh`) and it seems to fix the stoke weight issue for me for the SVG font.  Hence, this seems to be a bug in `picosvg`.

**Comment by dnlutz** [comment]
the overall curve quality looks much better now, thank you very much ; )

on my mac the color version works in textedit …
but not in all those adobe applications (indesign, illustrator, photoshop).
the black version is working perfect but it doesn't display the color version.

generally all major adobe applications should support ot-svg-color fonts by now:
https://helpx.adobe.com/fonts/user-guide.html/fonts/using/ot-svg-color-fonts.ug.html

do you have any idea what might cause this error?

**Comment by mavit** [comment]
> on my mac the color version works in textedit …
> but not in all those adobe applications (indesign, illustrator, photoshop).

Is this with the COPR/CPAL TTF, or the SVG TTF?  I think it’s likely that we’ll want to recommend one format of TTF for certain OSs/applications and another for others.

> the black version is working perfect but it doesn't display the color version.

I'm not sure what you mean by this?

**Comment by dnlutz** [comment]
it's the OpenMoji-Color.ttf font from [OpenMoji-exported_nanoemoji.zip](https://github.com/hfg-gmuend/openmoji/files/5391469/OpenMoji-experted_nanoemoji.zip) that doesn't work in the adobe applications. 

it shows up the font menu but it doesn't display any glyphs : /

**Comment by b-g** [comment]
@dnlutz please check again the newly exported fonts, especially the CPAL ones: 
[exported-openmoji-fonts-21-oct-2020.zip](https://github.com/hfg-gmuend/openmoji/files/5415902/exported-openmoji-fonts-21-oct-2020.zip)

@mavit Great! Building the fonts works nicely now. But we have to double check the quality ... and the maybe settle down on a single approach? Hence here is a list of how the current fonts are rendered in various browsers

# **Current OpenMoji fonts of 12.4**
(firefox, chrome, safari)
Screen Shot 2020-10-20 at 14 05 39
Screen Shot 2020-10-20 at 14 06 11
Screen Shot 2020-10-20 at 14 05 55

# **Work in progress OpenMoji fonts of this PR**
(firefox, safari, chrome)

Screen Shot 2020-10-20 at 11 24 30
Screen Shot 2020-10-20 at 11 24 05
Screen Shot 2020-10-20 at 11 24 56
Screen Shot 2020-10-20 at 11 26 41

**Comment by dnlutz** [comment]
unfortunately nothing works in indesign : /
the only version that shows up in the glyphs-palette is from the folder "untouchedsvgz"
but if it type something there are only empty white glyphs.
and if i rescale the glyphs-palette the glyphs also disappear.
Bildschirmfoto 2020-10-22 um 11 51 47

**Comment by dnlutz** [comment]
maybe we should reach out to @pauldhunt from adobe?
@RoelN also seems to be quite familiar with the subject …

**Comment by b-g** [comment]
@dnlutz but the one of OpenMoji 12.4 works in Adobe CC?

**Comment by dnlutz** [comment]
yes … after a reboot it works again ; )

**Comment by mavit** [comment]
The stroke width issue described in https://github.com/hfg-gmuend/openmoji/pull/260#issuecomment-710012849 turned out to be a [bug in picosvg which is now fixed](https://github.com/googlefonts/picosvg/pull/137).

Hereʼs a summary of what I believe to be the current situation:
- Both the colour COPR/CPAL TTFs and black and white TTFs built by nanoemoji work well on Linux, but do not work well on MacOS.  I donʼt believe theyʼve been tested on Windows.
- The colour SVG TTFs built using nanoemoji work adequately in Firefox but not sufficiently well in other applications.  They're probably not useful to us at the current time.
- The existing TTFs generated by scfbuild are much larger than those generated by nanoemoji, but are more compatible with various applications.

Does anyone have a computer running Windows they could test on?

**Comment by RoelN** [comment]
The CPAL font looks fine on Windows (shown here in wakamaifondue.com)

image

**Comment by b-g** [comment]
Hi @mavit, that's good news + Many thanks for the update! 

Just wanted to give it a try as well ... but getting this error now (see below).

Also could you do me a favor and make the filenames of the resulting fonts more verbose? I feel it is not so clear what for instance the file `picosvgz/OpenMoji-Color.ttf` actually holds in terms of standards. I think a filename like `OpenMoji-Color-COPR-CPAL`, `OpenMoji-Color-SVG` could streamline a little bit our discussion here. What do you think?

```
bene@zwei-207 openmoji % npm run generate-font

> openmoji@12.4.0 generate-font /Users/bene/Documents/openmoji
> ./helpers/generate-fonts.sh

master: Pulling from mavit/nanoemoji-container
ae7b613df528: Pull complete 
9970cf8663a9: Pull complete 
8f542e7556d7: Pull complete 
Digest: sha256:a38cd4692f0a104a9b2e002566a041d0d3f5fe012e10d4a8ab1de180674664af
Status: Downloaded newer image for registry.gitlab.com/mavit/nanoemoji-container:master
registry.gitlab.com/mavit/nanoemoji-container:master
FATAL Flags parsing error: Unknown command line flag 'color_format'
Pass --helpshort or --helpfull to see help on flags.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openmoji@12.4.0 generate-font: `./helpers/generate-fonts.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openmoji@12.4.0 generate-font script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bene/.npm/_logs/2020-11-30T10_23_51_450Z-debug.log
```

full log file:
[2020-11-30T10_23_51_450Z-debug.log.zip](https://github.com/hfg-gmuend/openmoji/files/5615382/2020-11-30T10_23_51_450Z-debug.log.zip)

**Comment by b-g** [comment]
Dear @mavit, just a random thought in terms of the bbox crop issue the COPR-CPAL fonts seem to have (at least on macOS). 

Could it simply be that in `helpers/generate-ttf.sh` we have to alter the `viewBox` attribute from 72 to 1.3 * 72 = 94 ... in order to make it display nicely everywhere. Did you try that?

96722316-86fe1300-13ad-11eb-985a-f3aa6163e1de


2020-12-03 at 11 21

**Comment by mavit** [comment]
> but getting this error now (see below).

Are you using the latest commit on this branch?

> Also could you do me a favor and make the filenames of the resulting fonts more verbose?

Done.

> Could it simply be that in helpers/generate-ttf.sh we have to alter the viewBox attribute from 72 to 1.3 * 72 = 94 ... in order to make it display nicely everywhere. Did you try that?

The font is scaled relative to this box, I think, so ultimately it doesn't help.  It cures the clipping issue, but takes us back to the situation where the characters are too small.

**Comment by b-g** [comment]
Hi @mavit, Many thanks for the latest improvements, this helps! I'm able to run it again on macOS. Could you also at the scaling up of the viewbox attribute to 72 to 1.3 * 72 = 94? I think it still worth to look into it and double check what the outcome would be exactly. Thanks!!

**Comment by mavit** [comment]
> Could you also at the scaling up of the viewbox attribute to 72 to 1.3 * 72 = 94

I tried it and it was as I described: the characters are too small.

**Comment by samhocevar** [comment]
FYI, I have tested the COLR/CPAL font in [Emoji.Wpf](https://github.com/samhocevar/emoji.wpf), a library that adds emoji support to WPF applications on Windows, and they work pretty well except for the bounding box issues. Here are two screenshots:

image
image

**Comment by b-g** [comment]
Hi @samhocevar, very nice! Emoji.Wpf 👍 ! I guess the bounding box issue could potentially be fixed by altering the `viewBox` attribute, see https://github.com/hfg-gmuend/openmoji/pull/260#issuecomment-737849368 ... I currently don't have time for it, but we are planing to re-visit the issue this summer. Feel free to propose something if you are by any chance into it ;)

**Comment by mavit** [comment]
The latest version of nanoemoji sizes characters differently, and it's possible that this has (or could be used to) fix our clipping problem.  I have pushed TTFs built with this version to this branch.  Could someone with access to MacOS re-test?

**Comment by samhocevar** [comment]
Works a lot better on Windows; here is the COLR TTF vs. Segoe UI Emoji. I noticed that all bounding boxes are square, not sure if that is intended or not. In the standard Windows font, emoji widths are non-square, which is too subtle for most glyphs to be noticeable but can be seen quite prominently on family emoji. Attached is a debug screenshot for reference (glyph width is computed from the X advance):

**Comment by dnlutz** [comment]
@mavit can you please post the test fonts?
then i could give it a try on mac os …

**Comment by mavit** [comment]
> @mavit can you please post the test fonts?

Look for the .ttf files in https://github.com/hfg-gmuend/openmoji/pull/260/files?file-filters%5B%5D=.ttf

**Comment by mavit** [comment]
> I noticed that all bounding boxes are square, not sure if that is intended or not.

I think this is probably because OpenMoji is compiled from square SVGs.  (Compare with https://github.com/googlefonts/nanoemoji/pull/255#issuecomment-796408885).

As I understand it, there are two different widths to consider: the width of the bounding box doesn’t have to be the same as the space between the start of this character and the start of the next character (the “advance width”).  Nanoemoji now has a setting that lets us tweak the latter independently of the former, if we want/need.  We can also make the characters appear smaller/larger and move them up or down relative to the baseline by tweaking the settings for ascender and descender.

**Comment by dnlutz** [comment]
got it … and tested it on mac os.
the black fonts looks good but the glyphs in the color font are incomplete : /
Bildschirmfoto 2021-03-26 um 15 11 16

**Comment by mavit** [comment]
>  the black font looks good but the glyphs in the color font are incomplete : /

Which format colour font was this?  SVG or COLR?  Could you try the other too?

**Comment by dnlutz** [comment]
it was the SVG version (OpenMoji-Black.ttf / OpenMoji-Color.SVG.ttf)
COLR only works on windows, i don't think i'm able to run it on my mac?

**Comment by mavit** [comment]
> COLR only works on windows, i don't think i'm able to run it on my mac?

We saw it working in a screenshot in https://github.com/hfg-gmuend/openmoji/pull/260#issuecomment-713549796.  Searching the web, it seems that it was added in MacOS 10.13, so presumably works in all currently supported versions.

**Comment by dnlutz** [comment]
OpenMoji-Color.COLRv0.ttf works in firefox and in textedit but not in adobe illustrator
OpenMoji-Color.SVG.ttf works only in firefox, the emoji glyphs are smaller than the COLR version

**Comment by mavit** [comment]
Great, looks like the clipping issue is solved.

Using `scfbuild` to build an SVG TTF for people on macOS who use Adobe apps, and `nanoemoji` to build a COLR/CPAL TTF for everyone else, I think there are no more remaining problems.

**Comment by b-g** [comment]
Hi @mavit, yes that hopefully could to the trick! Yay! Could you please add the container `ghcr.io/b-g/scfbuild` and potentially cleanup the PR ... so that I can easily check everything once more before merge? Cheers! :)

**Comment by mavit** [comment]
I've had a look, and I'm afraid this might be as tidy as I can make it (besides squashing to a single commit).

**Comment by yisibl** [comment]
nanoemoji can also build SVG in OT fonts

**Comment by mavit** [comment]
There has been a new release of nanoemoji, 0.8.0, which introduces the possibility to generate SVG TTFs with positioning, scaling, and lossless compression, but without lossy compression.  We believe that it was the lossy compression (in its current form) that was causing the problems for applications on macOS.

@dnlutz Could you test again, this time with https://github.com/hfg-gmuend/openmoji/raw/1a08cb61cc2bd827afd5bc6f968193b92eea2dcc/font/untouchedsvgz/OpenMoji-Color.SVG.ttf?  If this looks okay, then we should be able to drop scfbuild after all.

**Comment by yisibl** [comment]
Please try again with `--color_format=picosvg`. This will reduce the file size of the font.

**Comment by dnlutz** [comment]
o.k. … now i managed to test "OpenMoji-Color.SVG.ttf" on my mac.
everything looks fine in firefox (screenshot), but the font doesn't display any glyphs in textedit or adobe illustrator. what's interesting though: when i convert the openmoji text

 to paths then all emoji suddenly show up in illustrator.

**Comment by mavit** [comment]
Thanks for testing again.

The latest news from the nanoemoji project is that they think they now have SVG fonts built with their lossy picosvg compression working in Adobe apps and Safari.  Lets wait for them to release a version that includes these improvements, then we can try again.

**Comment by mavit** [comment]
Okay, there's another SVG TTF built with nanoemoji 0.8.1 at
https://github.com/hfg-gmuend/openmoji/blob/b4972b4ca68637a7899d1539bccfc7d97ec2eede/font/picosvgz/OpenMoji-Color.SVG.ttf.  Could someone test this on macOS, please?

I think we might be nearly there.  🤞

**Comment by dnlutz** [comment]
i'm sorry but basically the results are still the same:
the ttf font works in the browser but the glyphs are not displayed in textedit or in adobe illustrator.
… well they are displayed somehow in illustrator: far above the actual text field (screenshot)
is it possible to generate an otf font? maybe this would work better?
Bildschirmfoto 2021-04-26 um 16 14 21

**Comment by mavit** [comment]
> i have to admit that i just discovered an older copy of the openmoji font in a subfolder of my fonts folder (where it did not belong to – sorry!)

Ah, that's good to hear.  In that case, could you re-test https://github.com/hfg-gmuend/openmoji/blob/b4972b4ca68637a7899d1539bccfc7d97ec2eede/font/untouchedsvgz/OpenMoji-Color.SVG.ttf?raw=true

> in textedit i still discovered a bug though: some smileys and persons are not displayed (screenshot)
> Bildschirmfoto 2021-04-26 um 16 28 34

Does Safari do the same thing?  It sounds like this could have the same cause as https://github.com/googlefonts/nanoemoji/issues/276.

**Comment by dnlutz** [comment]
the re-test shows exactly the same result in textedit.
in firefox everything looks fine.

safari and chrome don't display any openmoji at all : /
there's nothing to see but "ABC XYZ Lorem ipsum" …
i'm sorry – but it looks like the struggle continues ; )

**Comment by mavit** [comment]
In that case, let's stick with using scfbuild for making SVG fonts for use on macOS.  We can still use nanoemoji for black and white fonts and COLR/CPAL fonts.

**Comment by gusbemacbe** [comment]
@b-g and @carlinmack 

I have tested @mavit's COLR font on Edge on Linux and it worked:

image

Cc: @jmontane

**Comment by gusbemacbe** [comment]
It also worked on VSCode editor and integral terminal, using COLR font. The flags used to not work on integrated terminal in reference to https://github.com/microsoft/vscode/issues/69900. 

image

**Comment by RobertWinslow** [comment]
Here's a COLRv0 OpenMoji Font updated to Emoji 14.0
https://github.com/Emoji-COLRv0/Emoji-COLRv0/blob/main/fonts/OpenMojiCOLRv0.ttf

Built using NanoEmoji. It's far from perfect, but may be useful to those who want a functioning color webfont to use right now.
It worked on all the browsers I tried on MacOS and Windows.
Here's a browser test page:
https://emoji-colrv0.github.io/Emoji-COLRv0/emojitable

**Comment by b-g** [comment]
Hi @RobertWinslow, many thanks for this! Did quickly check the browser test page ... looks quite good on macOS (Firefox, Safari and Chrome)! 

@dnlutz could you please double check the font in Adobe CC and Glyphs, too?

> Here's a COLRv0 OpenMoji Font updated to Emoji 14.0
https://github.com/Emoji-COLRv0/Emoji-COLRv0/blob/main/fonts/OpenMojiCOLRv0.ttf

**Comment by mavit** [comment]
Closing in favour of #422.

**Comment by dnlutz** [comment]
@JeppeKlitgaard

Sorry that it took some time but now i also checked you font files: 

MacOS 12.6 / Adobe Illustrator

OpenMoji-black-glyf.ttf
works in Adobe Illustrator. But the font contains a big number of glyphs without unicode encoding that contain chopped bits and pieces (screenshot).

OpenMoji-color-picosvgz.ttf
makes illustrator crash.

OpenMoji-color-untouchedsvgz.ttf
looks good and works fine in Adobe Illustrator.

Bildschirmfoto 2022-12-21 um 11 22 42

**Pull request closed without merging**
