### PR TITLE
Fix Unicode sequence for Catalonia flag.

### PR DESCRIPTION
**Pull request by samhocevar**
The flag is currently present as `1FEF4-E0065-E0073-E0063-E0074-E007F.svg` but `1FEF4` is not a valid Unicode character. The actual sequence starts with `1F3F4` instead.

### CODE REVIEW

**Comment by b-g** [comment]
Please help us and add a comment / be more verbose of what has been changed. Is the existing Unicode of Catalonia flag incorrect?

**Comment by b-g** [comment]
Also: tests are red. Run `npm run test-dev` to validate every PR.

**Comment by samhocevar** [comment]
Sorry about that, the tests pass for me, but since `CONTRIBUTING.md` said “Please submit only the files in `src` folder” I thought the rest would be autogenerated. I will amend the commit.

**Comment by b-g** [comment]
Great! Thanks for spotting this Unicode naming bug! Merged.

**Comment by jmontane** [comment]
Thank you very much!

**Pull request merged**
