### PR TITLE
tag isometric emoji

### PR DESCRIPTION
**Pull request by fuddl**
did I miss any?

### CODE REVIEW

**Comment by carlinmack** [comment]
the new mouse trap emoji is ortho too (it's in a recent commit), let me also check the openmoji library to find some more

**Comment by carlinmack** [comment]
ice too. I think that's all :)

**Comment by fuddl** [comment]
roll of paper maybe?

**Comment by carlinmack** [comment]
yeah I would say so

**Comment by carlinmack** [comment]
please add the tag to Ice too

**Comment by carlinmack** [comment]
I didn't realise this but we're actually referring to isometric! 

image

can you do a ctrl+h (find and replace) for orthographic -> isometric then I'll merge haha

**Comment by fuddl** [comment]
should totally be fixed in the [styleguide as well](https://openmoji.org/styleguide/#perspective) 😅

**Comment by fuddl** [comment]
outch, I have already deleted the branch

**Comment by fuddl** [comment]
to be continued in #187

**Pull request closed without merging**
