### PR TITLE
add creative commons

### PR DESCRIPTION
**Pull request by carlinmack**
Seeing as we use the CC license, we should add the newly added CC symbols

image

I've had a go, but I'm not happy with the CC-BY emoji (1F16F)

### CODE REVIEW

**Comment by b-g** [comment]
Great! This is typo will reach out to @dnlutz, he is the expert on it. Stay tuned!

**Comment by dnlutz** [comment]
for the CC-BY emoji (1F16F): version _3 is just great ; )

**Comment by dnlutz** [comment]
1F10E: here I would increase the opening on the left side.
But everything else looks very fine, thank you!

**Comment by carlinmack** [comment]
@b-g I can't do anything with this for some reason :( 
image

any luck for you?

**Comment by b-g** [comment]
@carlinmack no :( If I update from Master I could merge ... but then this seems to contradict a commit which deleted some of the cc emojis? I guess the simple solution is to extract the improvements in this PR and push them directly to Master. Sorry!

**Comment by carlinmack** [comment]
closed with 243482f9d353cfd2e566e787e103d65cd6706c07

**Pull request closed without merging**
