### PR TITLE
Fix emojis with speech bubbles to face correct direction

### PR DESCRIPTION
**Pull request by carlinmack**
#72 

image

Not failing due to my changes

### CODE REVIEW

**Comment by b-g** [comment]
@carlinmack Will wait with all merges until we have the tests fixed. Sorry!

**Comment by carlinmack** [comment]
One obvious problem with these right now is the lack of consistency in the way that the stem connects to the bubble. I think the spiky one has the most openmoji-consistent style but I didn't want to change the others without some discussion

**Comment by b-g** [comment]
Many thanks for this! Yes good that the directions are now aligned to other vendors, also I find it more consistent/better how you re-designed the way stem and bubble are connected. Nice!

Just I don't think it is a good idea to introduce a half circle for 1F4AC. As we try hard to stay with minimal shapes and always aim to reduce complexity. Also it would be more consistent with the other bubbles.

OK?

2019-12-04 at 13 55

(Also there is a merged conflict on the changelog now)

**Comment by carlinmack** [comment]
@b-g merging as I've changed from a semi circle to a full circle

**Pull request merged**
