### PR TITLE
Redesign of shrimp, butterfly, and turtle 🦐🦋🐢

### PR DESCRIPTION
**Pull request by RobertWinslow**
The redesign of the butterfly (1F98B) is as discussed in issue #342 

For the Turtle (1F422), I redesigned it to make it more similar to the other emoji sets.

For the Shrimp (1F990)... this is entirely subjective, but I just didn't feel like it was *shrimpy* enough. 

I already ran these three files through [the tester](https://openmoji-tester.glitch.me/test), (which currently seems to be down), and they passed the checks.

### CODE REVIEW

**Comment by dnlutz** [comment]
dear @RobertWinslow 
thank you for your contribution! we talked about the butterfly already, i also like the new turtle and shrimp!
i only have a few minor optimization suggestions:
Bildschirmfoto 2022-03-28 um 11 27 28
– expaning the color between the gaps of the black outline would especially help the turtle (png above)
– i would use the lighter green for the hole body of the turtle and reserve the darker green for the shell
– the new shrimp looks better but why not keeping the two different colors to make the segments more visible?

**Comment by b-g** [comment]
@RobertWinslow Many thanks for this! Also a tiny idea/comment: It might be nicer to have the feeler antennas of the the Shrimp (1F990) in red. You could use the special layer `color-foreground`for this, see e.g. the red frame of Bike and https://openmoji.org/styleguide/#submission

**Comment by RobertWinslow** [comment]
Thanks for the feedback. I expanded the colored bits to fill out the lines. And the shrimp color changes make it more consistent with the other OpenMoji crustaceans. Good call there. 
image image

I did keep the dark green on the turtle's belly though. That's his plastron. :)

**Comment by b-g** [comment]
@RobertWinslow Great!! Merged! Added you as the "designer" in data/enhancements-emoji-unicode-data.csv ... you might want to consider to submit your portrait for https://openmoji.org/about/#authors--team so that you are listed there as well.

**Pull request merged**
