### PR TITLE
Fix generating combined COLR/SVG fonts

### LINKED ISSUE #438: Combined COLR + SVG fonts aren't
The fonts in `font/OpenMoji-color-colr?_svg` are supposed to include both COLR and SVG tables, to make them compatible with more platforms/applications.  However, I was suspicious of their small file sizes, so:

```console
openmoji$ ttx -l font/*/*.ttf
Listing table info for "font/OpenMoji-black-glyf/OpenMoji-black-glyf.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    GSUB  0xA768C7BA     29020   1352472
    OS/2  0x44B70CEF        96       312
    cmap  0xA5DB68A4      5808     28528
    glyf  0xAE4A334E   1260729     90424
    head  0x24335FF3        54       188
    hhea  0x096B040B        36       244
    hmtx  0xBD209BBE     28120       408
    loca  0xF7A7C30B     56088     34336
    maxp  0x376D075D        32       280
    name  0x7E51B16C      1282   1351156
    post  0xFFB60033        32   1352440

Listing table info for "font/OpenMoji-color-cbdt/OpenMoji-color-cbdt.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    CBDT  0xC8EDAE38   5961329     24180
    CBLC  0xFBED0182     16412   5985512
    GSUB  0xA768C7BA     29020   6001924
    OS/2  0x44B70CEF        96       344
    cmap  0xA5DB68A4      5808      8764
    glyf  0x01FBC969        42     22820
    head  0x20E0823B        54       220
    hhea  0x0617076B        36       276
    hmtx  0x0F1E0033      8322       440
    loca  0xA911A911      8246     14572
    maxp  0x101D0009        32       312
    name  0x7E95B1B0      1282     22864
    post  0xFFB60033        32     24148

Listing table info for "font/OpenMoji-color-colr0_svg/OpenMoji-color-colr0_svg.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    COLR  0x7FAFF6AD    248214   2158980
    CPAL  0x8E96E08F       154   2407196
    GSUB  0xA768C7BA     29020   2407352
    OS/2  0x44B70CEF        96       344
    cmap  0xA5DB68A4      5808     74228
    glyf  0x66880091   1930205    227456
    head  0x25AC8494        54       220
    hhea  0x0AE40285        36       276
    hmtx  0x03320A67     73786       440
    loca  0x9465269B    147420     80036
    maxp  0x90320404        32       312
    name  0x7E95B1B0      1282   2157664
    post  0xFFB60033        32   2158948

Listing table info for "font/OpenMoji-color-colr1_svg/OpenMoji-color-colr1_svg.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    COLR  0xDDB8DB97    551852   1639984
    CPAL  0xEFF11B25       126   2191836
    GSUB  0xA768C7BA     29020   2191964
    OS/2  0x44B70CEF        96       344
    cmap  0xA5DB68A4      5808     41648
    glyf  0xC32F4325   1508947    129720
    head  0x24338453        54       220
    hhea  0x096B040B        36       276
    hmtx  0xB8097F92     41208       440
    loca  0xE3F9AEAF     82264     47456
    maxp  0x50880397        32       312
    name  0x7E95B1B0      1282   1638668
    post  0xFFB60033        32   1639952

Listing table info for "font/OpenMoji-color-glyf_colr_0/OpenMoji-color-glyf_colr_0.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    COLR  0x7FAFF6AD    248214   2158980
    CPAL  0x8E96E08F       154   2407196
    GSUB  0xA768C7BA     29020   2407352
    OS/2  0x44B70CEF        96       344
    cmap  0xA5DB68A4      5808     74228
    glyf  0x66880091   1930205    227456
    head  0x25AC8494        54       220
    hhea  0x0AE40285        36       276
    hmtx  0x03320A67     73786       440
    loca  0x9465269B    147420     80036
    maxp  0x90320404        32       312
    name  0x7E95B1B0      1282   2157664
    post  0xFFB60033        32   2158948

Listing table info for "font/OpenMoji-color-glyf_colr_1/OpenMoji-color-glyf_colr_1.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    COLR  0xDDB8DB97    551852   1639984
    CPAL  0xEFF11B25       126   2191836
    GSUB  0xA768C7BA     29020   2191964
    OS/2  0x44B70CEF        96       344
    cmap  0xA5DB68A4      5808     41648
    glyf  0xC32F4325   1508947    129720
    head  0x24338453        54       220
    hhea  0x096B040B        36       276
    hmtx  0xB8097F92     41208       440
    loca  0xE3F9AEAF     82264     47456
    maxp  0x50880397        32       312
    name  0x7E95B1B0      1282   1638668
    post  0xFFB60033        32   1639952

Listing table info for "font/OpenMoji-color-picosvgz/OpenMoji-color-picosvgz.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    GSUB  0x0A824BEA     29020     28936
    OS/2  0x44B70CEF        96       328
    SVG   0x1EA7136D   2806468     57956
    cmap  0xAFF7644C     10578      8748
    glyf  0x01FBC969        42     27576
    head  0x20E08295        54       204
    hhea  0x0617076B        36       260
    hmtx  0x0F1E0033      8322       424
    loca  0xA911A911      8246     19328
    maxp  0x101D0009        32       296
    name  0x7E95B1B0      1282     27620
    post  0xFFB60033        32     28904

Listing table info for "font/OpenMoji-color-sbix/OpenMoji-color-sbix.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    GSUB  0xA768C7BA     29020     24164
    OS/2  0x44B70CEF        96       328
    cmap  0xA5DB68A4      5808      8748
    glyf  0x01FBC969        42     22804
    head  0x20E08274        54       204
    hhea  0x0617076B        36       260
    hmtx  0x0F1E0033      8322       424
    loca  0xA911A911      8246     14556
    maxp  0x101D0009        32       296
    name  0x7E95B1B0      1282     22848
    post  0xFFB60033        32     24132
    sbix  0xB436C9A6   5973749     53184

Listing table info for "font/OpenMoji-color-untouchedsvgz/OpenMoji-color-untouchedsvgz.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    GSUB  0xA768C7BA     29020     24164
    OS/2  0x44B70CEF        96       328
    SVG   0x408CB041   4362827     53184
    cmap  0xA5DB68A4      5808      8748
    glyf  0x01FBC969        42     22804
    head  0x20E08294        54       204
    hhea  0x0617076B        36       260
    hmtx  0x0F1E0033      8322       424
    loca  0xA911A911      8246     14556
    maxp  0x101D0009        32       296
    name  0x7E95B1B0      1282     22848
    post  0xFFB60033        32     24132
```

It turns out that the supposedly-combined TTFs are actually identical to the COLR-only TTFs:

```console
openmoji$ cksum font/*/*.ttf
2206686862 1381492 font/OpenMoji-black-glyf/OpenMoji-black-glyf.ttf
0292600769 6030944 font/OpenMoji-color-cbdt/OpenMoji-color-cbdt.ttf
1345055486 2436372 font/OpenMoji-color-colr0_svg/OpenMoji-color-colr0_svg.ttf
2818145268 2220984 font/OpenMoji-color-colr1_svg/OpenMoji-color-colr1_svg.ttf
1345055486 2436372 font/OpenMoji-color-glyf_colr_0/OpenMoji-color-glyf_colr_0.ttf
2818145268 2220984 font/OpenMoji-color-glyf_colr_1/OpenMoji-color-glyf_colr_1.ttf
2337660750 2864424 font/OpenMoji-color-picosvgz/OpenMoji-color-picosvgz.ttf
1116599812 6026936 font/OpenMoji-color-sbix/OpenMoji-color-sbix.ttf
2438673327 4416012 font/OpenMoji-color-untouchedsvgz/OpenMoji-color-untouchedsvgz.ttf
```

### PR DESCRIPTION
**Pull request by 999eagle**
This change should fix the combined COLR/SVG fonts as `maximum_color` by default outputs the generated font to `build/Font.ttf` instead of changing the font file passed as argument directly. With this change, the output file is specified directly.

Fixes #438 

@b-g @RobertWinslow

### CODE REVIEW

**Comment by b-g** [comment]
Hi @999eagle, many thanks for this! Just ... I have a hard time to verify this, as I'm unfortunately not familiar with the nitty gritty details of the svg fonts. Sorry!

Hence @mavit @RobertWinslow could one of you please cross-check and confirm? (Or explain me how I could integrate this issue into our[ test suite](https://github.com/hfg-gmuend/openmoji/tree/master/test)?)

**Comment by b-g** [comment]
Hi @999eagle, hope you've had a nice summer! Could you please incororate PR #464 into this branch to test/verify whether your proposed fix doesn't fail the introduced font tests (basically runs `npm test` all green)? Thanks!

**Comment by 999eagle** [comment]
I've rebased this PR on top of #464, so if the tests pass now, it should work correctly.

**Comment by 999eagle** [comment]
I've regenerated all fonts locally and pushed the new `colr0_svg` and `colr1_svg` versions now. With this, `npm test` passes.

**Comment by b-g** [comment]
Hi @999eagle, many thanks for the COLR/SVG fix! Yay! 👍 🙏! Merged.

**Pull request merged**
