### PR TITLE
Add blue whale, move orca

### PR DESCRIPTION
**Pull request by kriskowal**
This change moves the existing orca and spouting orca into the private use area, then adds new blue whale and spouting blue whale to make the whale emojis more consistent with other interpretations.

### CODE REVIEW

**Comment by kriskowal** [comment]
Per Cetacean Proposal #161

**Comment by carlinmack** [comment]
Would it be possible for you not to include cdf6ece12421d648a9a3d3d21a1cc16e28201565? makes checking what you've actually changed very difficult

**Comment by kriskowal** [comment]
> Would it be possible for you not to include [cdf6ece](https://github.com/hfg-gmuend/openmoji/commit/cdf6ece12421d648a9a3d3d21a1cc16e28201565)? makes checking what you've actually changed very difficult

The commits are intentionally individually reviewable, but yes, I can. I will probably need to squash all the commits and attempt to isolate my changes.

**Comment by kriskowal** [comment]
> Would it be possible for you not to include [cdf6ece](https://github.com/hfg-gmuend/openmoji/commit/cdf6ece12421d648a9a3d3d21a1cc16e28201565)? makes checking what you've actually changed very difficult

@carlinmack done! 🙂

**Comment by cyberalien** [comment]
File 1F433.svg in this commit has a lot of non-standard attributes, such as `solid-color` and obsolete attributes such as `color-rendering`.

**Comment by kriskowal** [comment]
> File 1F433.svg in this commit has a lot of non-standard attributes, such as `solid-color` and obsolete attributes such as `color-rendering`.

Thank you for catching this. https://github.com/hfg-gmuend/openmoji/pull/168

**Comment by b-g** [comment]
@kriskowal Many thanks for the nice new blue whales! 🙏 Looks super!

**Pull request merged**
