### PR TITLE
Normalize trailing commas in data directory

### PR DESCRIPTION
**Pull request by waldyrious**
Just a small cleanup change: remove trailing commas within quoted lists. This was only present in a small minority of the entries, which were normalized to match the other ones.

### CODE REVIEW

**Comment by b-g** [comment]
@waldyrious Many thanks for spotting! Nice!! Merged

**Comment by waldyrious** [comment]
@b-g Thanks for the additional fixes to the PR! However, I noticed that a trailing comma was added [here](https://github.com/hfg-gmuend/openmoji/pull/388/commits/fdaed2590171ef515bf3c7d7e9f700e0fd262182#diff-ed3916d38301d22653c7041ac4d41cb4d3502abed000829a7fecd9c9dd1966f4R3753) and [here](https://github.com/hfg-gmuend/openmoji/pull/388/commits/fdaed2590171ef515bf3c7d7e9f700e0fd262182#diff-b64c39d02f7abc9982a99590c9239b9d8bac5422e2bcc6fef5420f2657b7e9ddR63776). What happened there?

Also, I have additional small fixes like these to submit, but also I might be able to contribute a substantial amount of data, as I mentioned [here](https://github.com/hfg-gmuend/openmoji/issues/125#issuecomment-1112109044). Would that be welcome?

**Comment by b-g** [comment]
@waldyrious This would be welcome :)

**Comment by b-g** [comment]
Please be aware of `npm run generate-data-tables.js`, see `helpers/generate-data-tables.js`. This script basically takes 

- data/enhancements-emoji-unicode-data.csv
- data/extras-openmoji.csv
- data/extras-unicode.csv

and combines with with data of the emojibase-data package ... and generates the openmoji.XXX files

**Pull request merged**
