### PR TITLE
adding polygons

### PR DESCRIPTION
**Pull request by loominade**
adding [yet another geometric shape](https://unicode-table.com/en/2BC3/). This time *hopefully* without errors.

### CODE REVIEW

**Comment by carlinmack** [comment]
If you're planning to do more, can you batch them and submit multiple under the same PR?

if this is the last one I'll merge it :)

**Comment by loominade** [comment]
Ok i will add all the equilateral polygons: ⬟⬠⯃⯄⬣

should I tag them with `polygon` or `equilateral polygon`?

**Comment by carlinmack** [comment]
what do you mean tag them?

**Comment by loominade** [comment]
`openmoji_tags`

**Comment by carlinmack** [comment]
do `"equilateral polygon"` 👍

**Comment by loominade** [comment]
✅

**Pull request merged**
