### PR TITLE
Fix webbed fingers of ok and pinching emoji

### PR DESCRIPTION
**Pull request by carlinmack**
#72 The effect is visible on dark backgrounds 

image

### CODE REVIEW

**Comment by b-g** [comment]
Many thanks! But I would like to discuss this with Daniel @dnlutz quickly. As it relates to one of the big open issues #31 ... the way forward might be simply a white additional outline around everything to differentiate our emojis properly on dark backgrounds.

**Comment by carlinmack** [comment]
Trying to mock that up now and it's harder than it seems hmm

**Comment by b-g** [comment]
@carlinmack Many thanks for this! But we will turn down this PR ... We think it is better to address and fix the issue in general and not just for a few ones. Sorry! Hope you understand.

**Comment by carlinmack** [comment]
yep it's a bigger issue than this PR

**Pull request closed without merging**
