### PR TITLE
added subdivision flags with bears

### PR DESCRIPTION
**Pull request by fuddl**
Berlin to California

### CODE REVIEW

**Comment by carlinmack** [comment]
the california bear could do with some improvements! This is a tricky design to get right; I think you should experiment with rounded corners and making the sillouhette look more realistic — The neck doesn't look anatomically correct

**Comment by fuddl** [comment]
@carlinmack how is this?
rounding the bear

**Comment by b-g** [comment]
Nice! But I would like to loop in @dnlutz as he did all the flags ... he also solved the dragon of the Wales flag https://openmoji.org/library/#search=wales&emoji=1F3F4-E0067-E0062-E0077-E006C-E0073-E007F.

**Comment by dnlutz** [comment]
Looks good! Can you simplify the bear even further? 
The head and the last leg on the right are still very detailed. 
OpenMoji Rule #1: The less anchor points, the better ; )

For the green meadow below: can you please give the object a green outline?
Then the corners will become less sharp (similar to the red star).

**Comment by fuddl** [comment]
@dnlutz I'm down to 37 anchors and you now have edit permissions 🙂

bear in pixel grid

**Comment by dnlutz** [comment]
Looks pretty good! You can definitely keep it that way. But if you want you could also give it a try and easily remove 5 to 10 more anchor points ; ) I'd rather not modify it myself (things won't get better when I start to edit in GitHub)

**Comment by fuddl** [comment]
I am down to 29 and on the edge of it stop being a bear. please review 😃

**Comment by carlinmack** [comment]
image

I think the most recent simplification goes too far in the neck area

btw you mention edit permissions but haven't posted a figma link

**Comment by dnlutz** [comment]
I also think so: head and neck were better before (the bear looked more bear-like ; )

**Comment by fuddl** [comment]
> btw you mention edit permissions but haven't posted a figma link

@carlinmack @dnlutz same link as last time: https://www.figma.com/file/sZZLEmdnMTOAxq0mTgO4WN/new-openmoji?node-id=119%3A0 🙂

**Comment by carlinmack** [comment]
I had a go

image

@dnlutz you can play around in browser here https://www.figma.com/file/sZZLEmdnMTOAxq0mTgO4WN/new-openmoji?node-id=119%3A0

**Comment by dnlutz** [comment]
It looks very good now! (the only anchor i would remove is the one below the neck ; )
Thank you for the Figma invitation. But I'm not used to Figma yet … so I tend to destroy things instead of improving them. But maybe one day I will evolve beyond Adobe Illustrator ; )

**Comment by carlinmack** [comment]
image

**Comment by fuddl** [comment]
@carlinmack done

**Comment by carlinmack** [comment]
final version :)
F3F4-E0064-E0065-E0062-E0065-E007F

**Comment by carlinmack** [comment]
🚀

**Pull request merged**
