### PR TITLE
Add transgender flag

### PR DESCRIPTION
**Pull request by carlinmack**
There is nothing wrong with this emoji but I want some advice on where to place it. It's already been given a unicode code point as far as I can tell and is in the draft for Emoji 13.0. Should this be placed in extra-openmoji still? or should I place it in the flags/flag directory?

https://emojipedia.org/transgender-flag/

### CODE REVIEW

**Comment by b-g** [comment]
Nice! I would recommend to do the following:

1. assign the unicode draft hexcode
2. add it to category extra-openmoji (for now)
3. add data/extras-openmoji.csv
4. mention it in the changelog

Once we do Unicode 13 we will have to move it to the final categories and move the data from data/extras-openmoji.csv to data/enhancements-emoji-unicode-data.csv

**Comment by carlinmack** [comment]
failing as no production files

**Comment by b-g** [comment]
@carlinmack Many thanks for the flag! I've added production files ... and merged it.
PS. Please `npm install` it seems you are using an outdated emojibase version :)

**Comment by carlinmack** [comment]
I'm not sure what you did but that commit is lost, it is no longer in the master branch

**Comment by b-g** [comment]
@carlinmack Sorry made a mistake! Commit (of transgender flag) is back and issue is resolved.

**Pull request merged**
